### ISSUE TITLE
Support Mac OS.X

### ISSUE THREAD

**Issue by luckyrat** [kee-org/KeeFox#22]
Use case: Mono 2.4 can run on Apple Mac computers, thereby enabling the use of KeePass 2.x on this operating system. It would be nice if KeeFox would work on this OS too.

Key work required is:

1) A compilation of the KeeFox C++ source code for a Mac OS.X machine so it can be loaded by the Linux version of Firefox. This may be as simple as running a Mac compiler but is likely to require some source code changes.

2) Some parts of the KeeFox? add-on may need review (especially w.r.t. directory separators in preference values).

3) An installation routine to assist Mac users with the installation and configuration of required components.

**Comment by plotters** [comment]
I tried to install KeeFox plugin 1.6.1b1 in Firefox 47.0 on OS X 10.11, but it doesn't want to install. Any ideas how to fix this? 

![keefox](https://cloud.githubusercontent.com/assets/11218863/16806942/dede8c14-4916-11e6-8311-8b304eb813e7.png)
