### ISSUE TITLE
Warning for expired KeePass entries

### ISSUE THREAD

**Issue by MonsieurBon** [kee-org/KeeFox#230]
I usually set an expiry date on KeePass entries as a reminder to change the password. KeeFox uses expired entries to log in without a notification. It would be nice if KeeFox showed a message like "Expired KeePass entry used for login" when an expired entry was used.

**Comment by tx3eh8IUD1** [comment]
+1 for the request :-)

**Comment by borys-p** [comment]
+1 here

**Comment by avtora** [comment]
yeah, it will be very helpful feature :+1:

**Comment by santiagofn** [comment]
+1

**Comment by WojTecH94** [comment]
Is it possible to add this small but really needed feature?

**Comment by lizhitwo** [comment]
Or even just changing the icon or adding a strike over text in the popup window would be helpful.
