### ISSUE TITLE
Usage tracking / Recently Used and Most Frequent

### ISSUE THREAD

**Issue by Danp2** [kee-org/KeeFox#258]
Coming from Roboform, I really miss the automatic lists of the Recently Used and Most Frequently Used logins. I read elsewhere where you stated that you intended to add some usage tracking that would allow these types of enhancements. Has this been done? If not, is it still on your list to be implemented?

**Comment by luckyrat** [comment]
I'm not intending to implement this in KeeFox and would need some convincing before accepting a pull request.

My main concern is over the privacy implications inherent with storing data about recently accessed URLs but it is also a complex feature to implement with very minimal benefit.

While the idea of a recently used list is technically interesting and has some benefit, other solutions can already deliver the same result, assuming a close correlation between frequently used logins and frequently accessed pages.

On its own, KeeFox offers a search box to help quickly filter through thousands of entries.

For those times when even that is too many key-presses given the frequency of one's access to certain URLs, Firefox has a very well tuned "recent URL" feature of its own which is available in the "new tab" page as well as countless independent add-ons.

When combined with KeeFox's auto-fill/submit feature, that approach completes the desired functionality with zero or one extra mouse clicks. Saving one click is not worth the privacy concern and months of development time.

In the rare cases where there is not a one-to-one match between web site and login, KeeFox features like priority and more accurate URL matching can get one even closer to the desired result and in the even rarer cases where that is not enough, the list of logins to choose from should be small or the KeeFox search will have far fewer to filter through so you won't be far from selecting the desired login.
