### ISSUE TITLE
Feature Request: Allow (remembered) dismissal of false form hits

### ISSUE THREAD

**Issue by zatricky** [kee-org/KeeFox#259]
Often a page has certain parameters in forms that are erroneously recognised as a user/pass. Auto-fill can then replace a valid pre-filled parameter with "junk" login information.

Rather than choose from the options "Not Now" or "Never for This Site", a third option, "Never for This Form" would go a long way in user experience. :)

An example is the "Search Settings" page in Sickbeard, where the "Search Frequency" parameter is recognised as a "username". Of course, this replaces the correct value (a number) with non-numeric data.

**Comment by luckyrat** [comment]
In many cases you could block a form from being filled in by adding its name or id to a site-specific blacklist. One relatively easy enhancement would be to expose this option in a more convenient way (e.g. right click on a form field and click an option to prevent filling forms on this site that have the same ID/name).

I think that idea needs more fleshing out and consideration about how it fits with other site-specific settings exposure like a way to force a form to be auto-fillable even if it has a more generally blacklisted name (like "search") and also how it is best to present the feature(s) to the user - context menu only or in some cases it might make sense to put something visible in the main panel.
