### ISSUE TITLE
HTTP Basic Authentication: more accurate URL matching

### ISSUE THREAD

**Issue by xchs** [kee-org/KeeFox#288]
How can I match a particular web address when it comes to **HTTP basic authentication**?

For example, I have a lot of web projects where certain areas, directories or web pages are password protected with HTTP Basic Auth:
- `http://example.com/project1/install.php`
- `http://foo.example.com/project2/install.php`
- `http://foo.example.com/project3/install.php`
- `http://bar.example.com/project4/install.php`

The relevant directives from the `.htaccess` look e.g. as follows:

``` apache
<FilesMatch "install\.php$">
  AuthName "Restricted area"
  AuthType Basic
  AuthUserFile /path/to/the/password/file
  AuthGroupFile /dev/null
  Require valid-user
</FilesMatch>
```

It would be nice if I could enable the _"Require more accurate URL matching"_ option and add the entire web address to the _"Additional URLs"_ section.

As it is now, KeeFox only checks for the hostname (`example.com`, `foo.example.com`, etc.) and the _"HTTP Auth Realm"_ entry.

**Comment by luckyrat** [comment]
Looks like this was left a little incomplete.

Unfortunately, Firefox does not provide a way for KeeFox to know the URL that actually triggered the HTTP Auth dialog box to appear. We can extract the host from the text displayed in the dialog but nothing else.

I've actually not checked to see if they have added anything to assist further with this in recent Firefox versions but there is still the terminally imminent threat of the dialogs being changed substantially such that they no longer block the entire browser (modal) so I don't want to invest any more time into this part of KeeFox unless something actually breaks.

I'm confident the situation will change and allow us to resolve this issue one day, I just have no idea when.

**Comment by xchs** [comment]
Okay, thank you for your efforts in this regard.
