### ISSUE TITLE
Find a way to save passwords for a http auth with no realm

### ISSUE THREAD

**Issue by Torlof** [kee-org/KeeFox#301]
Hi,

Keefox has problems saving the password for a microsoft share point portal. When I login at for example share.lrz.de (https authentification), keefox shows me the "do you want to save this password?" buttons at the top as usual, but when I click "save password" nothing happens. The boxes don't disappear, the login doesn't get saved, it just has no effect at all. Three of the four buttons don't have an effect, the only one working is "not now", which makes the buttons disappear, obviously...
The firefox password manager doesn't have any trouble saving passwords for this login.

Debug log:
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: Location changed.
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: Removing all matched logins
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: setupButton_ready start
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: Setting widget status
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: setupButton_ready end
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: onStateChange accepted
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: nouid
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: onStateChange: end
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: domEventListener: got event DOMContentLoaded
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: Returning configuration from cache
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: domEventListener: trying to load form filler
Sun Jul 06 2014 09:56:44 GMT+0200:INFO:  Filling document. Initial page load: true
Sun Jul 06 2014 09:56:44 GMT+0200:INFO:  attempting document fill
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: Returning configuration from cache
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: fillDocument processing 1 forms
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: about to get form fields
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: usernameIndex: -1
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: actualUsernameIndex: 0
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: otherFields.length:0
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: no password field found in this form
Sun Jul 06 2014 09:56:44 GMT+0200:DEBUG: domEventListener: form filler finished
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: prepareFill accepted
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: Removing the data that helps us track multi-page logins, etc.
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: clearTabFormFillData start
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: clearTabFormFillData end
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: Sending a JSON-RPC request
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: received message from web socket
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: starting decryption
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: decryption stage A took: 0
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: decryption stage B took: 1
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: decryption stage C took: 0
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: decryption stage D took: 1
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: decryption stage E took: 0
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: decrypt() called: 1404633406286
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: _commonCrypt() called
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: decryption stage F took: 2
Sun Jul 06 2014 09:56:46 GMT+0200:DEBUG: decryption finished
Sun Jul 06 2014 09:56:46 GMT+0200:INFO:  callback fired!
Sun Jul 06 2014 09:56:51 GMT+0200:DEBUG: Returning configuration from cache
Sun Jul 06 2014 09:56:51 GMT+0200:INFO:  Searching for logins
Sun Jul 06 2014 09:56:51 GMT+0200:DEBUG: Sending a JSON-RPC request
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: received message from web socket
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: starting decryption
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: decryption stage A took: 0
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: decryption stage B took: 1
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: decryption stage C took: 0
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: decryption stage D took: 0
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: decryption stage E took: 1
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: decrypt() called: 1404633412047
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: _commonCrypt() called
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: decryption stage F took: 1
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: decryption finished
Sun Jul 06 2014 09:56:52 GMT+0200:INFO:  callback fired!
Sun Jul 06 2014 09:56:52 GMT+0200:INFO:  password is not recognised so prompting user to save it
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: found window with name:
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: found window with name:
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: found a browser for this window.
Sun Jul 06 2014 09:56:52 GMT+0200:WARN:  Couldn't parse origin
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: Adding new password-save notification bar
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: Location changed.
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: Removing all matched logins
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: setupButton_ready start
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: Setting widget status
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: setupButton_ready end
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: onStateChange accepted
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: nouid
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: formSubmitTrackerCount > 0
Sun Jul 06 2014 09:56:52 GMT+0200:DEBUG: onStateChange: end
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: onStateChange accepted
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: nouid
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: formSubmitTrackerCount > 0
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: onStateChange: end
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domEventListener: got event DOMContentLoaded
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: Returning configuration from cache
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domEventListener: trying to load form filler
Sun Jul 06 2014 09:56:53 GMT+0200:INFO:  Filling document. Initial page load: true
Sun Jul 06 2014 09:56:53 GMT+0200:INFO:  attempting document fill
Sun Jul 06 2014 09:56:53 GMT+0200:INFO:  No forms found on this page
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domEventListener: form filler finished
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domEventListener: got event DOMContentLoaded
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: Returning configuration from cache
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domEventListener: trying to load form filler
Sun Jul 06 2014 09:56:53 GMT+0200:INFO:  Filling document. Initial page load: true
Sun Jul 06 2014 09:56:53 GMT+0200:INFO:  attempting document fill
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: Returning configuration from cache
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: fillDocument processing 1 forms
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: about to get form fields
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: text
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: proccessing...
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: checkbox
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: proccessing...
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: text
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: proccessing...
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: text
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: proccessing...
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domtype: hidden
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: usernameIndex: -1
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: actualUsernameIndex: 0
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: otherFields.length:4
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: no password field found in this form
Sun Jul 06 2014 09:56:53 GMT+0200:DEBUG: domEventListener: form filler finished
Sun Jul 06 2014 09:56:55 GMT+0200:ERROR: Exception occurred in menu item callback: Can't add a login without a httpRealm or formSubmitURL.

**Comment by luckyrat** [comment]
I still want to address this but it'll probably need to wait until Mozilla improve the HTTP Auth dialog boxes (permanently imminent so we shall see...)
