### ISSUE TITLE
Add option to invert login modifier key behaviour

### ISSUE THREAD

**Issue by luckyrat** [kee-org/KeeFox#308]
When middle (or CTRL-) clicking on a Login you can cause the login to be opened in a new tab/window. This enhancement would allow an option to set this as the behaviour when issuing a standard left-click instead.

**Comment by nrwilk** [comment]
This functionality is simple and I believe it is a mistake to exclude it. Will it ever be implemented?

Ctrl-clicking (or middle-clicking) Is not a feasible alternative for some of us.

**Comment by luckyrat** [comment]
I appreciate it's important for some people but it's not a mistake to exclude it if the time is instead spent on ensuring KeeFox continues to work with new versions of Firefox for everyone.

I'll accept a pull request that implements the feature (but note that current development work is based on the e10s branch so either fork from that or wait until that's merged into master sometime in the next few months).
