### ISSUE TITLE
KeyPass will not close with "X" button

### ISSUE THREAD

**Issue by HarrySeaward** [kee-org/KeeFox#323]
Here's how to replicate this issue:
1. Install KeeFox (plugin for Firefox) if not already installed.
2. Enable the KeePass option "Close button [X] minimizes main window instead of terminating the application".
3. Exit KeePass or lock the active databasse
4. Click on "Launch KeePass" or "Login to KeePass" from the KeeFox toolbar in Firefox.
5. Enter password.
6. Click the "X" button. (Nothing happens)

This issue does not happen if the option in #2 above is not enabled.

KeePass v.2.27
KeeFox v.1.4.2

The only OS's I've used KeyPass on are Win2k, WinXP and Win7. This issue has been present on all of them.

This issue has been present in every version combination of KeePass/KeeFox I've used since I started using KeePass 2 years ago.

**Comment by luckyrat** [comment]
I still can't reproduce this. I've tried on another machine (this time running Windows 7x64 with KeePass 2.29).

Maybe anyone with the problem should compare notes about what other similarities there are across the systems that exhibit this behaviour.

**Comment by tgp1994** [comment]
Just wanting to add since I've also seen this issue. In the past I've run Windows 7 Pro 64 bit, Windows 8.1 Pro 64 bit, and now Windows 10 64 bit. All OSes I've had this issue on. I've also gone through several Keepass versions experiencing this problem, the latest currently being 2.30. Perhaps there is an issue with the way Keepass is launched from Keefox versus launching it normally from the desktop?

**Comment by luckyrat** [comment]
Still no luck reproducing it on my test machines.

Do any of you have any other software installed on your machines that might interfere? I know it's difficult to know what is worth mentioning but some examples might be:

* Other KeePass plugins
* Security software (antivirus, firewall, EMET, sandboxing frameworks)
* Desktop window management software (e.g. for enhanced multiple-desktop/monitor functionality)

**Comment by tgp1994** [comment]
I have had Norton 360 on one of my 8.1/10 machines, but otherwise I'm fairly certain I've just had Security Essentials. No other KP plugins or desktop window management software.

**Comment by Geepup** [comment]
I'm facing this issue already for ages. Just upgraded to 2.32 hoping it's gone, but no. I'm wondering if there is some kind of resolution or way to avoid it. I am using ChromeiPass, not Keefox, but I don't see that is causing the problem. Any ideas?
