### ISSUE TITLE
Login problem with CapitalOne website

### ISSUE THREAD

**Issue by icholas** [kee-org/KeeFox#339]
Hello,

I noticed that after I saved my login credentials for my CapitalOne account to KeePass using the KeeFox browser extension, that an authentication error occurs when trying to use KeeFox to login. The login page can be found here: https://servicing.capitalone.com/c1/login.aspx?CountryCode=CA I have confirmed that the login credentials are correct, so it appears that maybe KeeFox isn't filling the fields correctly.

Thanks

**Comment by thethereza** [comment]
having same problem  - still doesn't work if you copy and paste manually into capital one's online form (they just updated it - used to work) either so capital one is doing something stupid.

**Comment by seascape** [comment]
Same problem here. Capital One ended up locking my account due to the series of failed logins my KeeFox troubleshooting produced. Glad it's a bug and I'm not going crazy. :)
