### ISSUE TITLE
Make KeeFox entries in a web page's Context Menu optional

### ISSUE THREAD

**Issue by kirk-l** [kee-org/KeeFox#381]
Can you add an option to remove KeeFox's entries in the context menu? (Entries like "Generate new password," which I'd like to remove.) It can be all or nothing if necessary, or maybe on a per-item basis. (I just read about the "Detect forms" entry for form elements, which I might use.)

**Comment by luckyrat** [comment]
Yeah it could be done. Each KeeFox command can be associated with any combination of keyboard shortcut and context menu position. Right now I've only had time to implement the ability to modify the keyboard shortcuts of a fixed set of commands but the underlying code supports far more customisation.

Thanks for the vote of interest in this feature, I'll accept a pull request if someone wants to implement it and maybe get around to it myself in future if there's a bit more demand from other users to prioritise this above other features.

**Comment by BlueMax** [comment]
This drives me crazy. Regarding the locale properties the entry should be 'copyNewPasswordToClipboard' and it is found in `keefox@chris.tomlinson\chrome\content\options.js`, `keefox@chris.tomlinson\chrome\content\panel.js` and `keefox@chris.tomlinson\modules\commands.js`. I've disabled all blocks related to that entry but its still showing up in Firefox.

How can we disable it?

**Comment by defkev** [comment]
+1 as this is annoying as fuck

@BlueMax
In **modules\commands.js** uncomment the for-loop within the setupListeners from line **658** to **701** too stop KeeFox from populating the context menu:

```javascript
this.setupListeners = function (win)
{
/*
    for (let i=0; i<this.commands.length; i++)
    {
    ...
    }
*/
```

Additionally in **chrome\content\context.xul** uncomment the overlay from line **16** to **46** to remove the now obsolete separator and empty menu items:

```xml
<!--
<popup id="contentAreaContextMenu">
...
</popup>
-->
```

Cheers

**Comment by BlueMax** [comment]
Nice, thanks! :)

**Comment by BlueMax** [comment]
Unfortunately, it has side effects. When closing Firefox with multiple tabs open the confirmation dialog can't be accepted (null button).

**Comment by defkev** [comment]
Haven't seen any side effects yet.
What FF version are you running? 44.0.1 here.
Any other Addons installed tinkering with your context menu?
As this sounds like a xul problem to me.
