### ISSUE TITLE
Support for Placeholders added by other Keepass Plugins

### ISSUE THREAD

**Issue by alphafalcon** [kee-org/KeeFox#383]
I have recently installed the KeeOTP Plugin in KeePass which adds management of Time-Based-OneTimePasswords.
It also adds a new Placeholder for AutoType {TOTP} which is replaced by the currently valid OTP.

I tried using the {TOTP} Placeholder in KeeFox' "form fields" tab, but this just results in filling the field with {TOTP}.

Would it by possible to add placeholder parsing to the form field values?

**Comment by luckyrat** [comment]
It's possible but I don't think I'll get around to doing it so someone else would have to implement it.

I think we'd have to add some kind of config whitelist to ensure that only specific KeePass entries are processed in this way because resolving placeholders is very time consuming so doing it for all entries would probably break KeeFox, especially for large databases on slow PCs.

**Comment by nonojoeli** [comment]
Would it be that bad to additionally check for "{.*}"-Tokens in Text-Fields? I tried it on my PC and it works well - besides I don't know the performance impacts of this. My diff for the test was:

`diff --git a/KeePassRPC/KeePassRPCService.cs b/KeePassRPC/KeePassRPCService.cs
index 39af7e8..1603d5a 100644
--- a/KeePassRPC/KeePassRPCService.cs
+++ b/KeePassRPC/KeePassRPCService.cs
@@ -407,7 +407,12 @@ private LightEntry GetEntryFromPwEntry(PwEntry pwe, EntryConfig conf, int matchA
                             }
                         }
                         else
-                            formFieldList.Add(new FormField(ff.Name, ff.Name, ff.Value, ff.Type, ff.Id, ff.Page));
+                        {
+                            string ffValue = ff.Value;
+                            if (ffValue.StartsWith("{") && ffValue.EndsWith("}"))
+                                ffValue = KeePassRPCPlugin.GetPwEntryStringFromDereferencableValue(pwe, ffValue, db);
+                            formFieldList.Add(new FormField(ff.Name, ff.Name, ffValue, ff.Type, ff.Id, ff.Page));
+                        }
                     }
                 }
             }
`

**Comment by telepath** [comment]
I'd really like to test this, my database has ~800 entries. But i cannot compile the plugin myself currently, it would be great if someone could compile it for me!

**Comment by pkoevesdi** [comment]
I want to strongly support this feature request. AutoType workswell with TOTP, but Kee doesn't. :-(
