### ISSUE TITLE
Feature Request: "Require More Accurate URL Matching" bulk modification / defaulting

### ISSUE THREAD

**Issue by mikebriggs2k** [kee-org/KeeFox#387]
Problem:
I am a support technician and I visit numerous customer sites that we support and I'm having issues with username and password data being populated in strange form fields. The easiest way for me to fix this issue is to enable the "Require More Accurate URL Matching" option in the entry for that site. This becomes problematic when I have over 100 sites I visit that I have to modify that setting one at a time.

Story:
As a KeeFox user, I'd like a way to either set the default state of the "Require More Accurate URL Matching" option or modify entries in bulk to enable/disable the feature.

**Comment by luckyrat** [comment]
Let's revisit this after KeeFox 1.5 is released so we can make a call on the priority after testing out the hopefully improved form filling algorithm.
