### ISSUE TITLE
FF Hangs at 25% utilization (i5) when unlocking keepass

### ISSUE THREAD

**Issue by victor-50** [kee-org/KeeFox#437]
In general, for about a month FF is getting buggier and stalls often. This is especially the case if I unlock Keepass, FF being active and (mostly) a tab is open for which an entry exists. It then hangs completely and I have to restart from taskmanager, with no opportunity to get debugging info. 

Apart from that (maybe better as a separate issue) a lot of sites keep changing their login screen/procedure making it ever more difficult or even impossible to use KeeFox and in any case having to add the new procedure, there being no option to update an existing one properly. I have to consider returning to FF for managing my passwords.

**Comment by luckyrat** [comment]
Do you have any other addons or plugins installed? Have you checked for malware recently?

It sounds like something is interfering with some of the basic Firefox features that KeeFox relies upon. I can't really say anything more than that without a lot more detail though. If clearing out other addons, plugins, etc. doesn't help, maybe try enabling debug [logging](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Options-%7C-Logging) to a file and see if that tells us anything. At least it might give an indication what the last thing KeeFox managed to do was.

For your 2nd point:
#109
#319
and for those sites that have become impossible to use with KeeFox, at least some of them should start working again in KeeFox 1.5 (maybe after you re-save a new password - it'll depend on the exact website).

**Comment by luckyrat** [comment]
Small chance this is related to #539
