### ISSUE TITLE
username text file not being recognized at https://support.logitech.com/en_us/home#login

### ISSUE THREAD

**Issue by thx1200** [kee-org/KeeFox#441]
The username field is not recognized at https://support.logitech.com/en_us/home#login

At first, I thought it must use a weird non-standard ID, so I looked into the HTML and added the custom ID to site-specific settings (j_id0:template:j_id10:j_id13:j_id14:username) for https://support.logitech.com.  Then I did "detect forms" just in case and tried again many times.

Even with that explicit entry, it does not detect it.

Related, it doesn't detect 'offer to save passwords' for that page when you manually enter the username and password.  I'm assuming for the same reason.  It does detect the password field fine, though when you fill it out.

Am I doing something wrong?  I wasn't clear if custom ids and names supported any wildcarding or regex, or if there was another way to do this.  I also wasn't sure if the colons in the name were causing issues.

Side note: "site specific settings" isn't very discoverable... Maybe an option to put a button in the drop-down?  It took me like 10 minutes to figure out it was a hyperlink in the settings first page because I wasn't paying very close attention to the instructions.

And lastly, I read that site specific settings i the right place to non-standard ids, but there's also the section in KeePass for KeeFox that has "form fields" and I messed with that too, to no avail, but it didn't allow me to specify {username} as values to custom text fields, so I'm pretty sure I don't know what that section is actually for at all! :-)

**Comment by luckyrat** [comment]
The main problem is that the "submit" button is not actually a button. The form itself does not have a submit button which is a rare but not unique fault with that particular site (another symptom is that you can't just press enter on the keyboard to submit the form like with nearly every other form on the internet).

There is a possibility of one day being able to allow some user configuration to identify which element on the page is supposed to be the submit button but that's a big piece of work for a relatively small gain so it might not ever happen.

I created a basic KeePass entry with a username and password and the URL you supplied and then when loading the page, the form was auto-filled (for reasons described above, auto-submit will not work).

I've only tested in the preview build of KeeFox 1.5 so it might not work in KeeFox 1.4.x - install the KeeFox beta version if you want to try out a 1.5 build once it's ready for beta testing.

>  I wasn't clear if custom ids and names supported any wildcarding or regex

They don't

>  I also wasn't sure if the colons in the name were causing issues

They shouldn't but it's not a heavily used feature so there's a tiny chance I'm wrong. Either way, it's not the cause of this specific problem.

> "site specific settings" isn't very discoverable

Agreed. My plan to improve this is to provide more entry points such as #401, #448 and #449 and no doubt a few other ideas with the aim that actually navigating to the full settings page will be necessary in fewer situations. I don't think it's required frequently enough at the moment (and especially not after those other improvements) to demand regular attention from all users on the main menu panel.

> but it didn't allow me to specify {username} as values to custom text fields

You can just add an ID or name value to the username entry in the list. Or if you ever worry about duplicated field data, you might want to insert a field reference to a custom field: http://keepass.info/help/base/fieldrefs.html
