### ISSUE TITLE
Factor field @autocomplete values into match relevance scores

### ISSUE THREAD

**Issue by luckyrat** [kee-org/KeeFox#454]
When a site provides autocomplete attribute values to aid form filling accuracy we should use them.

Exact details need fleshing out but the overall idea would be to say that fields with a "username" attribute are more likely to be a match against the username data in the KeePass entry.

Conversely, a field with an obviously irrelevant @autocomplete value (e.g. "street-address" or "postal-code") would receive a significant penalty.

There are also password related hints so we can prioritise password fields with values like "password" or "current-password" and penalise ones like "new-password".

See https://html.spec.whatwg.org/multipage/forms.html#autofill-field for the list of values we should consider.

Mozilla appear to be working on something called getAutocompleteInfo() which might save us some of the trouble of parsing attribute string values but I don't think it actually exists yet and documentation is non-existent. Hence I'm not going to commit to looking at this issue immediately.

**Comment by iamhammer** [comment]
May we get a status update on this enhancement, or your understanding of the state of Mozilla's Autocomplete mechanization? Thank you
