### ISSUE TITLE
Move KeePassRPC json from strings to binary attachments

### ISSUE THREAD

**Issue by dlech** [kee-org/KeeFox#482]
Storing the data as a string tends to pollute the KeePass UI in other places. For example, in the main window, all of the strings are shown in the bottom pane. If you ever unhide protected strings, KeePassRPC JSON is really long and gets in the way. Also some plugins and 3rd party ports also make use of strings.

The data can easily be stored using the binary attachments instead of custom strings. The user can even still open it for viewing/editing in KeePass using the built-in text editor. I actually made the switch a while back in my KeeAgent plugin and it was really easy.

Also see: https://sourceforge.net/p/keepass/discussion/329220/thread/03a3901b/?limit=25&page=2#3e83

**Comment by luckyrat** [comment]
Yeah I'm definitely up for this. I'd like to think about any possible problems for a bit first but it's already in the back of my mind as a possible improvement for a KeeFox v2 that can cut ties with various other legacy components. Whether we do this as part of 1.6 and then remove the backwards compatibility in v2 or just put the whole lot into v2 or just make v1.6 actually be v2, I'm not sure yet.
