### ISSUE TITLE
Remove menu from pop up notification

### ISSUE THREAD

**Issue by a-polivanchuk** [kee-org/KeeFox#502]
The pop up notification looks huge and ugly, because it contains menu in it's bottom part.
![2015-07-03 08_33_56-](https://cloud.githubusercontent.com/assets/7978799/8493268/875b17ac-2160-11e5-8091-be54dff399fe.png)

I think the notification souldn't contain menu inside.
It should be just notification, like it was in previous versions.

**Comment by luckyrat** [comment]
Thanks for the feedback.

Funnily enough, many people have said that the old notification system was huge and ugly (more so for users with smaller screens I think) but that's not say that the new one can't be too!

I tried to retain the earlier notification system but there were many cases where it is incompatible with the upcoming (e10s) changes to Firefox (not to mention that the vastly improved "save password" feature would not be possible with the old approach) so just in case it was a consideration for you or anyone else, switching back to the bar-style notification system is not on the cards.

There are a couple of tangential improvements I'm hoping to work on next week which might reduce some of the usability impact of the new approach. #498 & #499

It might be possible to display the popup in a separate panel similar to the way the save password notification works (shifting it into the main menu panel if the user ignores it) but I think it will be a complicated task not without its own disadvantages so if the only downside of the current approach is a visual aesthetic, I probably won't be able to make time to change this before the stable v1.5 is released.

Please try to think if there are any frustrations or usability problems that come from the current v1.5 approach or whether some other visual adjustments might reduce that feeling of "huge and ugly".

I have an idea that might produce a similar effect to a complete removal of the menu but I won't have time to assess its feasibility until at least next week and I'd prefer to hear some more detailed feedback from you and other beta testers before revealing it (it will be interesting to see if anyone else comes up with the same thoughts independently).
