### ISSUE TITLE
Thunderbird ask for google calendar login (OAuth2) on every start

### ISSUE THREAD

**Issue by rsiggi** [kee-org/KeeFox#511]
Thunderbird: 38.1.0
Addons: Lightning 4.0.1
Tested with Keepass 1.5.3b3 und 1.4.8.1-signed

In a new profile I create a new google Calendar (as caldav) as described [here](https://developers.google.com/google-apps/calendar/caldav/v2/guide#connecting_to_googles_caldav_server) (a email-account isn't necessary). After restart Thunderbird do not ask to login. All runs as expected.
After installation the Keepass add-on,Thunderbird ask for start to relogin into the google account. If I disable the KeePass add-on, all runs without questions to relogin.

**Comment by dlech** [comment]
This is an unfortunate side effect of KeeFox. By enabling KeeFox in Thunderbird, the built-in option to remember passwords in Thunderbird itself is disabled. When you disable/uninstall KeeFox, this setting is reverted.

KeeFox 1.5.x, will automatically fill in the username and password for the google oauth dialog if it finds a matching login (assuming you are using the "Provider for Google Calendar" add-on). You still have to click a few buttons though, which is less than ideal, but not too bad.

**Comment by rsiggi** [comment]
With OAuth2 I also have to fill the verification code, apparently I have to accept.

**Comment by dlech** [comment]
Could you post a screenshot so that we can see exactly what you are talking about?

**Comment by rsiggi** [comment]
I see I have to change my test enviroment (keefox plugin), because me firefox used always 1.4.8.1. I will test this tomorrow.

**Comment by Azuvector** [comment]
I'm seeing this issue too, though I've not tested without the Provider for Google Calendar extension.

Details here, along with steps to reproduce the issue: https://groups.google.com/forum/#!topic/provider-for-google-calendar/3Wv_Up0k-H8

I'd assumed this was an issue relating to the Provider For Google Calendar extension, but perhaps not?

**Comment by adrianf0** [comment]
I have the same issue. I am ready to help with testing.

**Comment by adrianf0** [comment]
The problem hasn't been solved so far. Moreover, it doesn't fill password, even following tips in #511.
There is a related ticket on Lightning [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1154256)
Could KeeFox simply pass Google Provider authentication request to Thunderbird which stores OAuth2 token for the calendar anyway?

**Comment by Mad-at** [comment]
I have the same problem, please could someone have a look at this? Can I provide any more Information on this?

**Comment by adrianf0** [comment]
@luckyrat: What kind of info do you need? With @Mad-at we are ready to help.

**Comment by dlech** [comment]
Due to the recent split between Thunderbird and Firefox extensions, we have started a fork of KeeFox specifically for Thunderbird. We are calling this new extension KeeBird and the code and issue tracking are now in a new GitHub repository. If anyone is still interested in getting this issue resolved, please let us know by opening a new issue at https://github.com/kee-org/keebird/issues and copy/paste any relevant information (or at least link to this issue).
