### ISSUE TITLE
Support KeepassX integration

### ISSUE THREAD

**Issue by Rewarp** [kee-org/KeeFox#523]
Perhaps this is more complicated than it sounds, but I hope there would be support for KeepassX in KeeFox, particularly now that the beta1 of version 2 for that password manager has been released.

Also posting this here so I can post a bounty for this issue on BountySource.

**Comment by luckyrat** [comment]
If you want to write something to communicate with KeeFox, you'll need to port the KeePassRPC plugin (at least the protocol, if not the GUI). Depending on the libraries available in C++, it could be fairly straight forward but if you've got to write your own JSON-RPC, websocket and crypto implementations it could get complicated quickly, not to mention much more risky. Documentation can be found here: https://github.com/luckyrat/KeeFox/wiki/en-|-Technical-|-KeePassRPC-detail

If you've got any questions regarding that, let me know and I'll try to help when I can but I definitely won't have time to develop support for the KeePassX port myself.

**Comment by Rewarp** [comment]
Thanks for responding. I regret I do not have the skill set to write the implementations. But I would be glad to kick in a few bucks into the hat and hope someone would be willing to give it a shot.

**Comment by drankinatty** [comment]
Luckrat, I think this is important to. Both KeePassX and KeePass .kdb password databases have been compatible between both Linux and Windows versions for close to a decade. There is no reason this compatibility should not extend to KeyFox. Further, KeyFox should offer/(but NOT attempt on its own) to use the current .kdb password store in use by the user. What also seems smart is providing a way to import some (but NOT all) username/password entries from an existing .kdb for use in KeyFox. KeyFox should then allows saving the .kdb backend to the users existing .kdb location under a separate database name.

**Comment by luckyrat** [comment]
KeeFox is unconcerned with kdb or kdbx databases but it needs to talk to KeePassRPC, which can only run on .NET/Mono as a plugin for KeePass 2, which in turn requires .NET/Mono and uses the more advanced kdbx file format.

Any deviation from this would be a completely new add-on with barely any resemblance to KeeFox and likely require years of development work to get to a stable state but if you'd like to do that you are welcome.

**Comment by luckyrat** [comment]
As I said, I'm happy to help if I can with this issue but don't intend to do it myself. @Rewarp do you know if I can close this issue without affecting the bountysource listing?

I'll not actually close it until we're sure there are no external repercussions but I effectively consider it closed now.

**Comment by Rewarp** [comment]
I think it would close the issue on Bounty Source, since the bounty is paid out to the developer(s) who close the issue, pursuant to whether the backers accept the claim. Perhaps setting it as a wishlist would be something to consider?

I understand it can look pretty annoying, and offer my sincerest apologies for the inconvenience caused.

**Comment by luckyrat** [comment]
No worries. The "invalid" label will help me filter it out when necessary. I'll never get to 0 open issues anyway ;-)

**Comment by bitstreamout** [comment]
As I really like to avoid to install mono and I'm happy with KeepassX and it fully desktop integration I suggest to set it back at least to somewhat different then "invalid"  ;^)

**Comment by soredake** [comment]
https://github.com/keepassxreboot/keepassxc/issues/88

**Comment by colans** [comment]
All: Switch to [KeePassXC](https://keepassxc.org/) and then you won't have this problem anymore.
