### ISSUE TITLE
Thunderbird asks for outgoing server (SMTP) password everytime 

### ISSUE THREAD

**Issue by ktchong** [kee-org/KeeFox#528]
KeeFox can automatically log into IMAP just fine.  However, every session I want to send an email, Thunderbird would ask for the password for the SMTP server, which is the same as the IMAP server -- i.e., it is the same email account.  

Any help to get KeeFox to automatically fill in the password for outgoing SMTP mail?

Windows is 10. Thunderbird is 38.2.0.  KeePass is 2.3.  KeeFox is 1.4.8.1.

**Comment by dlech** [comment]
You need to upgrade to KeeFox v 1.5.x. See #388.

**Comment by dlech** [comment]
In #388, @ktchong said:

> I installed KeeFox 1.5.3b9. It did not work. It failed to even fill in the initial login for IMAP in Thunderbox.

> P.S. I actually tried installing 1.5.3b9 a couple days ago, which didn't solve my problem so I reverted to the 1.4.x. signed version.

Since #388 is closed, let's continue the discussion here.

What language are you using in Thunderbird?
