### ISSUE TITLE
KeeFox making firefox use >100% CPU on Linux when not set up properly

### ISSUE THREAD

**Issue by zovt** [kee-org/KeeFox#550]
Hey, I haven't gotten around to setting up KeeFox properly on linux yet, but I've noticed that since I haven't set it up, it's causing firefox to use >100% CPU, probably polling for a KeePass connection.

**Comment by luckyrat** [comment]
This is probably a duplicate of #539 although perhaps not if you can confirm that the problem goes away after you update the KPRPC plugin version to 1.5.3
