### ISSUE TITLE
Slow Browser

### ISSUE THREAD

**Issue by elcosca** [kee-org/KeeFox#563]
When I safe too many passwords in the database, my browser it slows. Please fix it

**Comment by luckyrat** [comment]
Please provide more information about the problem, how we can reproduce it, in what way it slows down, when you do what, etc.

**Comment by fabriziodicandia** [comment]
After having installed KeeFox my browser become quite slow.. I also have a big database, with more than 130 entries. I don't know which info might be useful to understand the problem, so AMA so I can help more!

EDIT: I think it might be useful to note my current addons: NoScript, uBlock Origin, HTTPS Everywhere and Chrome Store Foxified. I also have the LastPass addon, but I disabled it while trying KeeFox. (If you are wondering: yes, it works fine, it just seems to have slowed down a lot my browser experience.)
