### ISSUE TITLE
Keefox no longer working fully on ing.nl

### ISSUE THREAD

**Issue by MPE2016** [kee-org/KeeFox#584]
L.S.,

When trying to log in using keefox (and keepass), it will only fill the username field. Password field is left untouched. Keefox used to work on this site in the previous version of keefox. 

Autoptyping via keepass does result in filling both fields, so I'm pretty sure it's a keefox problem. 

Any advice? Many thanks in advance. 

On every other website, keefox is working very well, and I am otherwise a very happy user of this wonderful add-on!

**Comment by bert-hulscher** [comment]
Hoi Maarten,
De vraag is of het wijs is om voor deze site het password door KeePass te laten invullen, maar indien je hier bewust voor kiest kun je dit op de volgende manier oplossen.
Open in het menu van KeeFox "instellingen", dan het tabblad "Records bewaren". Ga hier naar de link "Wachtwoord specifieke instellingen" bij "Schakel wachtwoord opslaan bericht uit".
Vink hier "Biedt aan op wachtwoorden op te slaan" aan (zal default al zijn aangevinkt). Ik verwacht dat je links de site van ING al ziet staan. Zo nee, voeg dan de URL toe (htps://mijn.ing.nl). Klik op deze URL. Rechts krijg je nu de mogelijkheid om nogmaals "Biedt aan op wachtwoorden op te slaan" aan te vinken. Je ziet hier twee vakjes staan die beide moeten worden aangevinkt.
Hierna "Webpagina instellingen opslaan" en als je (via Close) terugkeert naar het tabblad "Records bewaren" ook hier op OK klikken (dus tweemaal bevestigen, althans zo heb ik het gedaan).
Daarna zou het moeten werken.
PS: zelf verwijder ik voor ik bovenstaande uitvoer eerst betreffend voorkomen in KeePass zodat KeeFox geforceerd wordt om het voorkomen met de nieuwe instellingen op te slaan.
Succes

**Comment by maartenpelgrim** [comment]
Hallo Bert,

Bedankt voor je antwoord! Overigens leuk om iets van een Nederlands 
sprekend iemand te horen ivm zoiets als Keepass; ik ben nog redelijk 
nieuw met open source software en linux, maar ik ben nog niet veel 
Nederlanders tegengekomen.
     Ik heb zelf ook getwijfeld of ik mijn  ING-wachtwoord moet invoeren 
in de database, maar ben uiteindelijk overstag gegaan omdat ik meen dat 
de risico's redelijk klein zijn, gezien iedere verdere actie gekoppeld 
is aan het bezit van mijn mobiele telefoon: betalingsbevestigingen, 
wijzingen van mijn gegevens etc. zijn allemaal onmogelijk zonder de 
telefoon. Of zie ik iets over het hoofd?
     Wat betreft je suggesties; die zal ik zeker ter harte nemen! Heb je 
er bezwaar tegen dat ik je nog een vervolgvraag stel, indien nodig?

In ieder geval nogmaals hartelijk dank!

Vriendelijke groet,

Maarten Pelgrim

Op 08-01-16 om 18:41 schreef bert-hulscher:

**Comment by bert-hulscher** [comment]
Hoi Maarten,
Natuurlijk mag je nog vervolgvragen stellen.
Ik had geen puf om mijn reactie in het Engels te schrijven en het kon niet anders dan dat jij Nederlander was.
Zelf heb ik KeePass (pas) sinds dinsdag geïnstalleerd (stond genoemd in uitgebreid artikel in het NRC) en heb me wel meteen verdiept in de mogelijkheden. Dat wat jij met ING tegenkwam heb ik zelf ook ervaren, middels bovenstaande opgelost maar toen weer disabled.
Ik gebruik KeePass op mijn laptop en dan is de kans groter dat iemand anders even "de besturing overneemt", anders dan bij gebruik op smartphone.
Mvg,
Bert Hulscher
