### ISSUE TITLE
KeeFox Upgrade doesn't connect in Windows 7

### ISSUE THREAD

**Issue by cl-nasa** [kee-org/KeeFox#586]
KeeFox was connected to KeePass at first install.  Following upgrade, KeeFox will launch KeePass but the number exchanges do not pop up.  Didn't work at home with Win 7, doesn't work at work either with Win 7 Enterprise SP1.  I do not see any pop-unders.  This has been a problem for me with older versions as well; then removing and reinstalling all software restores the pop-up boxes and the two can be reconnected.

**Comment by LaxrMediumWas** [comment]
I have a similar issue. One of my three profiles won't upgrade, it keeps asking to shut keepass but does nothing thereafter.

**Comment by luckyrat** [comment]
Maybe KeePass is not being closed correctly?

Can the problem be resolved after a computer restart?

I take it that you both see the setup KeeFox page at chrome://keefox/content/install.xul?upgrade=1 ?

**Comment by cl-nasa** [comment]
Yes, in Firefox I see the page chrome://keefox/content/install.xul?upgrade=1
On my home machine, KeyFox  is now working, without ever needing help to connect to the database, and with no other intervention.  I was surprised to see this resolve, that isn’t my past experience.
On my work machine, I am not routinely the administrator.  KeeFox displays the Upgrade KeeFox screen, then authorization fails, but KeePass opens, Setup KeeFox screen shows.  KeeFox has no access to the database.  But this is probably as expected.

**Comment by luckyrat** [comment]
There might be two different issues here. I think one of them is due to confusion related to #585

**Comment by luckyrat** [comment]
Does the problem go away in KeeFox 1.6?

https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/beta

If not, please provide more information if you'd like me to look into a particular problem.

**Comment by cl-nasa** [comment]
KeePass 2.30 and KeeFox 1.5.4 were producing chrome://keefox/content/install.xul?upgrade=1 the setup KeeFox screen.
Updated KeePass to 2.31 on Windows 7 Enterprise.  Installed the beta 1.6.0b1 KeeFox.  Still browser opens to chrome://keefox/content/install.xul?upgrade=1 .  Try opening KeePass from KeeFox, it opens.
Clicked on “upgrade” for KeePass RPC.  Completes upgrade but doesn’t connect.  Close KeePass and FireFox.  Reopen FireFox, use KeePass to reopen KeePass.  KeePass opens and connects to KeePass with errors, orange webpages, and no need to re-link KeePass and KeeFox.
