### ISSUE TITLE
Fails to accept Exchange EWS Provider plugin dialogs

### ISSUE THREAD

**Issue by naevtamarkus** [kee-org/KeeFox#587]
Dear devels,

I have a small problem trying to integrate Firefox and KeePass (with KeeFox) with the "Exchange EWS Provider". Everything else works as expected (I manage passwords for all my accounts) but with that plugin I was not able to succeed.

The plugin shows the dialog, but KeeFox ignores it (does not fill it up). This is the error shown by KeeFox:

```
Tue Dec 15 2015 10:32:49 GMT+0100 (CET):WARN: Couldn't parse origin
Tue Dec 15 2015 10:32:56 GMT+0100 (CET):WARN: KeeFox failed to process the data submitted to a dialog. Exception: TypeError: url is undefined
```

The thing is that the dialog shown by that plugin shows the URL correctly INSIDE the window (it says "Enter password for username on https://mailserver.domain.com/EWS/Exchange.asmx" but it does not seem to be enough (you tell me!). The title of the dialog reads "Microsoft Exchange EWS: Password request.". I have checked other (working) dialogs and they all seem to tell the URL in many different visible forms with no obvious format... so I don't know how to proceed. I have also opened an Issue with the guys from the plugin, hoping that either one or the other figure out where the problem might be.
Any ideas? Is the "url" you expect something to be in the title, the content, or anywhere else that might not be visible?

Thanks for looking into this,
BR/Pablo

**Comment by dlech** [comment]
First, are we talking Firefox or Thunderbird here? Second, you hinted that this is part of a plugin. Do you have a link to this plugin?

If this dialog does in fact come from a plugin, then KeeFox would have to be modified to be aware of this plugin to enable matching.

**Comment by naevtamarkus** [comment]
This is about Thunderbird... the plugin I mention is https://github.com/Ericsson/exchangecalendar

I also opened an Issue with them, thinking that the problem could be on either side... but if you tell me you need to adapt KeeFox then I should go and close the issue with them (please let me know).

Thanks!

**Comment by dlech** [comment]
I had a quick look and this plugin uses unconventional methods for getting the strings for this dialog.

https://github.com/Ericsson/exchangecalendar/blob/ca727839bdc59bfd0ad59fa7556abaeb9ceb159a/interfaces/exchangeAuthPrompt2/mivExchangeAuthPrompt2.js#L746

The title is hard-coded, which could be dealt with, but the other text comes from some source that I am not familiar with (which doesn't seem to be in the plugin itself).

https://github.com/Ericsson/exchangecalendar/blob/ca727839bdc59bfd0ad59fa7556abaeb9ceb159a/interfaces/exchangeAuthPrompt2/mivExchangeAuthPrompt2.js#L39

You might be better off using the KeePass auto-type function for this one.

**Comment by naevtamarkus** [comment]
Thanks for the hint. I just tried but unfortunately I could not make it work. The window is not detected by KeePass's Auto-Type feature (neither typing the title by hand or in the drop-down list).

Besides, the title does not contain the URL, so KeePass will type my password on any window from that plugin regardless of the account it's trying to use... this is not a good idea if you use more than one account.

Why does it matter how does the plugin get the strings into the dialog? I can send you a screenshot if you need, but the text is: ```Enter password for my_username on https://mailserver.domain.com/EWS/Exchange.asmx``` which contains the url. Is that what you need?

Thanks!

**Comment by dlech** [comment]
It would be best if we could figure out where the template for that string is coming from. What if someone is using a language other than English?

To make this work, you would have to add something [here](https://github.com/luckyrat/KeeFox/blob/master/Firefox%20addon/KeeFox/chrome/content/commonDialog.js#L310). But, since the Exchange EWS Provider addon doesn't use string bundles for the title and other text, you would have to make a fake string bundle object that provides the `GetStringFromName` function so that it could be passed to `LoadDialogData`.

**Comment by naevtamarkus** [comment]
I think we can ask them! They are just around the corner, let me post a comment on my issue into this one :)

**Comment by bavincen** [comment]
hey guys,
What kind of support do you need?
dtd is used for language translation purpose. We are also using stringbundle in someplaces. 

the passwords are saved like in the row like Username,Url,password? i guess you can view them using password editor.
is there any change needed.

**Comment by dlech** [comment]
@bavincen, We are trying to do string matching on the dialog title and text to be able to extract the username and url. As mentioned [here](https://github.com/luckyrat/KeeFox/issues/587#issuecomment-164831851), the dialog title is hard coded, it does not come from a dtd. This is OK as long as it never changes.

So the question left to be answered is: where does the text template `Enter password for <username> on <server>` come from? I don't see it in any dtd file. What is `1st-setup.nl/global/functions`? It looks like that is where the text is coming from.

**Comment by bavincen** [comment]
ahh ok!
Here the string comes from, we are directly calling a mozilla api 
windows watcher for password prompt.
https://github.com/Ericsson/exchangecalendar/search?utf8=%E2%9C%93&q=EnterPasswordFor
https://github.com/Ericsson/exchangecalendar/blob/ca727839bdc59bfd0ad59fa7556abaeb9ceb159a/interfaces/exchangeAuthPrompt2/mivExchangeAuthPrompt2.js#L753
|
This file is part of XPCOMM. I guess that's why they hard-coded it.
|||
On 12/17/2015 8:53 PM, David Lechner wrote:
>
> @bavincen <https://github.com/bavincen>, We are trying to do string 
> matching on the dialog title and text to be able to extract the 
> username and url. As mentioned here 
> <https://github.com/luckyrat/KeeFox/issues/587#issuecomment-164831851>, the 
> dialog title is hard coded, it does not come from a dtd. This is OK as 
> long as it never changes.
>
> So the question left to be answered is: where does the text template 
> |Enter password for <username> on <server>| come from? I don't see it 
> in any dtd file. What is |1st-setup.nl/global/functions|? It looks 
> like that is where the text is coming from.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/luckyrat/KeeFox/issues/587#issuecomment-165564203>.
>

-- 

	
Bavincen
Programmer, Ericsson
p: m: a: IN
s: http.:/*.*/bavincen e: bavincen.in@gmail.com, babu.vincent@ericsson.com

**Comment by dlech** [comment]
Thanks. That means "EnterPasswordFor" actually comes from http://mxr.mozilla.org/mozilla-central/source/toolkit/locales/en-US/chrome/global/commonDialogs.properties#31, so to answer my previous question, it is localized.

**Comment by bavincen** [comment]
Yes, I think so, sorry got no time to check that stuff,,


On 12/17/2015 9:28 PM, David Lechner wrote:
>
> Thanks. That means "EnterPasswordFor" actually comes from 
> http://mxr.mozilla.org/mozilla-central/source/toolkit/locales/en-US/chrome/global/commonDialogs.properties#31, 
> so to answer my previous question, it is localized.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/luckyrat/KeeFox/issues/587#issuecomment-165573647>.
>

-- 

	
Bavincen
Programmer, Ericsson
p: m: a: IN
s: http.:/*.*/bavincen e: bavincen.in@gmail.com, 
babu.vincent@ericsson.com 
<mailto:bavincen.in@gmail.com,%20babu.vincent@ericsson.com>

**Comment by dlech** [comment]
So, to implement this, we need to do what I said [here](https://github.com/luckyrat/KeeFox/issues/587#issuecomment-165177523) using the existing `_cdBundle` with `"EnterPasswordFor"` as `aPromptPropertyName`. But instead of adding the hard-coded title, we could just ignore the title for this dialog type (`aTitlePropertyName` == `null`), but some modification will be needed to make that actually work.

**Comment by naevtamarkus** [comment]
Don't know if this helps, but here it is just in case: the dialog has the name of the plugin in the title, that does probably not get translated... right?

**Comment by dlech** [comment]
Correct. (As I already pointed out, it is hard-coded, so won't change unless the code changes)
