### ISSUE TITLE
KeeFox from PPA does not work with FireFox >= 43 because it is not signed. (Linux-only)

### ISSUE THREAD

**Issue by dlech** [kee-org/KeeFox#589]
This is actually a problem with the packaging (which I maintain separate from KeeFox) and not something that @luckyrat is responsible for, but I just wanted to post here so that others might find it.

I just upgraded to FireFox 43 on Linux and it disabled the KeeFox plugin that was installed by the `xul-ext-keefox` package because it is not signed.

I am not sure how to fix this because signing an addon requires an Internet connection. The way the ppa works, I upload source code and it is built on launchpad in an environment without an Internet connection. In fact, the build will fail immediately if you try to fetch anything from the web. So, the package can't be signed via AMO when it is built.

If anyone knows a way to self-sign an addon in a way that doesn't require an Internet connection, let me know. Until then, I'm afraid this is going to remain broken.

**Comment by dlech** [comment]
It looks like Ubuntu's solution is to include a signed .xpi in the source. It's not a very good option, but it's an option.

**Comment by erhandsome** [comment]
about:config 
set xpinstall.signatures.required false

**Comment by luckyrat** [comment]
@erhandsome That's a temporary workaround for individual users but won't work for more than another version or two of Firefox.

**Comment by dlech** [comment]
Correct. `xpiinstall.signatures.required` is supported in FF 43 (current version) but won't be in 44 and beyond - unless you have the developer version of Firefox. I also tried signing the modified .xpi, but it failed because is has the same ID as the official version on AMO. I could change the ID in the ppa version, but then people could install both the PPA version and the AMO version at the same time, which would be bad.
