### ISSUE TITLE
erases username and password of entry after update

### ISSUE THREAD

**Issue by dkebler** [kee-org/KeeFox#591]
Not sure if this started 1.53 or 1.54.  As you know keefox keeps pesting me to update my entry (even when there is nothing to update).  If I oblige now it erases the username and password from the entry no matter which update type I choose.

Luckily I can keep resurrecting them from the history but since keefox now refuses to be quiet about this "update entry" I have to keep dealing with and remind myself to never update the entry.

Running lastest firefox on ubuntu with of course 1.5.4 and rpc of the same.

**Comment by luckyrat** [comment]
I don't really understand what the issue is here but if it goes away when KeeFox only offers you to update an entry when the username or password has changed then the KeeFox 1.6 beta will be of interest to you: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/beta
