### ISSUE TITLE
KeeFox intro tip box breaks popup layout

### ISSUE THREAD

**Issue by BoffinBrain** [kee-org/KeeFox#613]
Screenshots taken using a new, blank profile.

When the Getting Started Guide help box appears at the top of the popup, it makes the whole popup 3x as wide.

![keefoxtipultrawide](https://cloud.githubusercontent.com/assets/13255058/12919207/f57bcdd4-cf3a-11e5-80dd-43ab29b7ab8a.png)

When the KeePass toolbar button is contained within the Firefox menu, the contents of the box are clipped and unreadable without using the horizontal scrollbar, which probably shouldn't even be there.

![keefoxtipinsideffmenu](https://cloud.githubusercontent.com/assets/13255058/12919209/f7f7919c-cf3a-11e5-99ff-021cc160df17.png)

**Comment by luckyrat** [comment]
Which Firefox version? Mozilla might have changed something recently - KeeFox doesn't have much control over how it is rendered in the main menu but there's a small chance we might be able make it wrap into the small space.

It is designed to take up a decent amount of space when possible so around 3x as wide as normal sounds ideal when Firefox displays the KeeFox panel on its own.

**Comment by BoffinbraiN** [comment]
This is on version 44 using Windows 7.

In my opinion, the 3x width makes the menu buttons look rather silly since they don't need to be so wide. :)
