### ISSUE TITLE
Keefox does not setup on firefox 44.0.1

### ISSUE THREAD

**Issue by BrunoMCBraga** [kee-org/KeeFox#616]
Hi
I typically download firefox in Portuguese because, well, i am Portuguese. I have downloaded the English version but i cannot seem to get Keefox to work there, as opposed to the Portuguese version. When the setup starts, it stays stuck in; "The files required to setup KeeFox are being downloaded...". Why is this happening. It looks like it is stuck.

Best regards

**Comment by luckyrat** [comment]
Is it the same KeeFox version apart from the language?

It's worth trying to clear your internet cache (ctrl-shift-del and ensure "Cache" is selected and a long enough time period - probably "everything")

**Comment by luckyrat** [comment]
This is probably a duplicate of #633 (I'm guessing that the Firefox version number also increased rather than you just switching from one language to another).
