### ISSUE TITLE
(Auto-)Filling Patreon Log-in form disables the Submit button

### ISSUE THREAD

**Issue by elgonzo** [kee-org/KeeFox#617]
When KeeFox auto-fills the Log-in form of Patreon (https://www.patreon.com/login), the submit button becomes inactive.

Note that Patreon's Submit button is not a button of type "submit". Rather it is an ordinary button where some click handler is doing the actual log-in process (apparently, Patreon is using AngularJS to generate the Log-in page).

I guess that whatever KeeFox does on a page when finding and filling form fields is upsetting some script on Patreon's Log-in page, effectively disabling the Submit button.

(Unfortunately, neither the web console nor the browser console of Firefox did show any error or log message which i could relate to this issue :( )

KeeFox 1.5.4
FireFox 44.0.1 x64
Windows 7 Pro x64, english

**Comment by Bidouleroux** [comment]
Ran into this with KeeFox 1.6.3 on both Firefox 47 and 48 just now.

Log in web console shows `14:21:57.915 "[Amplitude] [Exception... "<no message>"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: https://www.patreon.com/login?redir=1 :: nrWrapper :: line 95"  data: no]"1amplitude-2.10.0-min.gz.js:2:3435`

I'm attaching the KeeFox log. I reload the page at 14:28, forms fill up fine. Then at 14:30 I hit the "Submit" button and nothing happens.
[log.txt](https://github.com/luckyrat/KeeFox/files/429004/log.txt)

**Comment by soundsfromsound** [comment]
I can confirm this as well. Using KeeFox on Firefox 50.1.0 still has this issue, the only fix is to simply manually type in email and password. Then submission works correctly. 

But as of now, Keefox is still not working with Patreon. Hope this helps someone.

**Comment by BrockA** [comment]
You can manually defeat this kind of idiocy by:

1. Click in the username field.  Type a space and then hit backspace.

**Comment by BrockA** [comment]
You can manually defeat this kind of idiocy by:

1. Use Keepass to fill in the username and password.
1. Click anywhere in the username field.  Type a space and then hit backspace.
1. Then click in the password input; type a space and hit backspace. 

There are automated ways around this too, ranging from autotype to usercripts. I haven't applied this to Patreon yet, so don't include the details here (yet).

**Comment by levicki** [comment]
@luckyrat Please see this issue reported to AngularJS:
https://github.com/angular/angular.js/issues/3133

In short, the issue is that DOM events are not triggered from KeeFox and AngularJS doesn't enable the Submit button.

Quoting developers:

> The current implementation of AngularJS listens to the input event on browsers that support it and has a fallback strategy for ones that don't. Relevant piece of the code here:
> https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L413

I hope you can do something to enable auto-fill properly for sites that use AngularJS for login form.
