### ISSUE TITLE
Specific login form, only password is populated

### ISSUE THREAD

**Issue by tleepa** [kee-org/KeeFox#619]
Hi,

My company uses single sign on solution that causes KeeFox to fill in only password field.
I have been playing around the KeeFox entry options (changing name and id of the username field) but to no avail.

Perhaps it is because of the login form is actually made of two forms?:

``` html
<!-- text box display -->
<tr>
  <form name="frm1" action="blank" onSubmit="defaultSubmit(); return false;" method="post">
    <td>
      <div class="logInp">
        <input type="text" name="IDToken1" id="IDToken1" value="" class="TxtFld">
      </div>
    </td>
  </form>
</tr>        
<!-- end of textBox -->

<!-- password display -->
<tr>
  <form name="frm2" action="blank" onSubmit="defaultSubmit(); return false;" method="post">
    <td>
      <div class="logInp">
        <input type="password" name="IDToken2" id="IDToken2" value="" class="TxtFld" autocomplete="off">
      </div>
    </td>
  </form>
</tr>        
<!-- end of password -->
```

Is there anything that can be done to overcome this?

BTW - using KeeFox 1.6 beta on Firefox.

**Comment by luckyrat** [comment]
KeeFox only fills in one form at a time. I've never seen a login system like this before and I doubt it could ever be made to work seamlessly. However, you might be able to create two separate KeePass entries and given accurate enough name/id configuration you could get one field filled in first, then select the other entry to fill in the 2nd field. It looks like they use javascript to submit the form though so it might not be possible to get KeeFox to auto-submit it for you (if not, you'll just have to click on whatever "login" button they present elsewhere on the page).

**Comment by tleepa** [comment]
Thank you for the answer :)
