### ISSUE TITLE
Keefox

### ISSUE THREAD

**Issue by Clay33** [kee-org/KeeFox#624]
It doesn't work I want it of!
It didn't even download!
Why is this thing up and there were no warnings about it even though ts old as hell!

**Comment by dlech** [comment]
I can see that you are frustrated, but it is not clear what is the problem you are trying to solve?

* What did you do already?
* What did you expect to happen?
* What actually happened?

**Comment by rybarova** [comment]
I have same problem. Keefox only says: can't join in database. How I can connect keepass with keefox?
