### ISSUE TITLE
Please, accept Bitcoins donations

### ISSUE THREAD

**Issue by Nogreedy** [kee-org/KeeFox#627]
Please, accept Bitcoins donations.
More and more websites accept now Bitcoin donations...
You can setup a Bitcoin wallet in minutes and show your Bitcoin public address easily.
Bitcoins are now accepted by 100,000 merchants worldwide.
Thank you for your answer.

**Comment by chronometric** [comment]
Couldn't be simpler, since you don't need complex checkout functions, go with Coinbase. They're the biggest, and transfer to and from your bank. Also some of the cheapest fees because of their size and legitimacy.

**Comment by skorokithakis** [comment]
Stripe is another great option.

**Comment by luckyrat** [comment]
I've set up a coinbase account here: https://www.coinbase.com/luckyrat

Thanks for the suggestion of Stripe but it appears to require custom development work and I only have a few minutes to spare so have gone for the coinbase approach.

Thanks in advance for any donations!

**Comment by skorokithakis** [comment]
Sent, thanks for a great plugin!

**Comment by Nogreedy** [comment]
Great.
I sent a little Bitcoin donation.
Is it possible for you to add the link https://www.coinbase.com/luckyrat to your homepage to inform users you accept Bitcoins donations?
