### ISSUE TITLE
Angular Apps do not detect input

### ISSUE THREAD

**Issue by bdurrer** [kee-org/KeeFox#638]
An increasing amount of webpages use Angular JS to build their Login-Forms. Sadly, Angular is not able to detect input from KeeFox (mostly noticeable because of the required-validation failing).

I guess the Issue is because Angular holds it's own data model and only updates it upon interaction. KeeFox's way of setting the values seems not to trigger the onChange event though.

In MY angular login forms I explicitly load username/password with jQuery. But we cannot expect every developert to do this and I doubt that angular changes it's behaviour in near future.

Request: make KeeFox work with angular.

Sample Page:
https://ebanking.raiffeisen.ch/entry/#/login

**Comment by luckyrat** [comment]
Over the past year I've seen more and more websites requiring user interaction with a form field before enabling the login button so perhaps this goes some way to explaining why it is becoming a trendy website "feature".

I have no idea how or if we can "make KeeFox work with Angular" but it certainly sounds like something we should investigate.

**Comment by bdurrer** [comment]
BTW: the guys at angualrjs do have a similar issue, because the browser's own autocomplete feature does not trigger any events: https://github.com/angular/angular.js/issues/1460

I don't know how KeeFox fills the input fields, but the problem might be the same (not generating onchange events). Maybe KeeFox needs to trigger onChange events explicitly?

**Comment by luckyrat** [comment]
Thanks for the link.

I see two problems with triggering onChange events:

1. Firefox does not so there may be a reason (I had always assumed onChange events only fire in response to user interaction so raising the event in this situation may be going against spec and just cause new problems). I don't think this prohibits KeeFox from taking this approach but it definitely needs more investigation into whether this is the right thing to do.
2. Apps may not have set up their listeners when KeeFox fires the event. Again, it's not necessarily a show-stopper but if we find that Angular apps and most other frameworks always initialise in a way that prohibits them listening for these events when KeeFox fires them, there's not much point in us implementing the feature.

**Comment by bdurrer** [comment]
1. You are correct, onChange are usually only raised by user interaction. And thats exactly the problem, JavaScript applications have no way to know that the input field has changed and won't update their underlaying model.

2. I don't think that would be a big issue. If nobody catches an onChange, it won't break anything. But I can see the possibility of breaking when a onChange is registered as HTML attribute but the matching function is not yet loaded (eg because it's in an external script).
With angular apps, KeeFox runs way to early anyway. Especially when external HTML Templates are used (which mostly is the case), the input fields are not yet there when KeeFox runs. Often, you have to do a "scan" or select the Login manually.

So I guess it would be unwise to trigger onChange events on every login page. Maybe what we need is an option to turn triggering of onChange this on for specific pages. 
And maybe a second option to run a delayed form-detection to cover the fact that angular may load its views asynchronously later?

**Comment by hrobertson** [comment]
DockerHub doesn't appear to use Angular but the login form is very Javascripty so I figured it falls under the same issue.

https://hub.docker.com/login/

Would it be possible to have KeeFox invoke the auto-type feature for selected websites? (eg. Specified under KeePass Entry/KeeFox tab/General tab/Entry Behaviour)

**Comment by ppascher** [comment]
I have the same problem with a React App (javascript) I wrote. I have to manually trigger an onChange event to get the forms to work with KeeFox.

**Comment by DanCech** [comment]
I'm experiencing the same issue with React apps using "controlled" form inputs.  They work by attaching a handler to the onChange event for the inputs and using the value to update internal state within the store.

https://facebook.github.io/react/docs/forms.html#controlled-components

This is going to become a more serious issue as React apps become more prevalent, especially as controlled inputs are the recommended approach.

It seems that this is sufficient to make onChange work in React (it's triggered by the native `input` event, not by the native `change` event):
```
element.value = 'test';
element.dispatchEvent(new Event('input', { bubbles: true }));
```
I'm not sure about Angular, it may be necessary to also dispatch a `change` event if Angular listens for that rather than `input`:
```
element.dispatchEvent(new Event('change', { bubbles: true }));
```

**Comment by bdurrer** [comment]
I made a JS Fiddle for Angular, where the issue is reproducible: 
https://jsfiddle.net/65np6dge/6/
- It demonstrates that **both events (input, change) make angular update it's model** of that one given field. 
- Other fields are not updated (which I guess is good as well). 
- Subsequently firing the events without changing the value is ignored by angular (which is a good thing too).


I know several banks which have their login page for their ebanking built with angular. 
So yes, I think KeeFox should fire one or both events on any field it changes.

**Comment by ebugusey** [comment]
Well, Firefox actually seems to fire onChange events:
https://jsfiddle.net/0q19zbxb/
I have changed type of password filed to `password`. Because Firefox doesn't otherwise doesn't recognize this form for autofill.
I say KeeFox should replicate what browser does in this case.

**Comment by bdurrer** [comment]
@ebugusey 
What do you mean by "Well, Firefox actually seems to fire onChange events:"?
You mean FireFox's internal password manager?

**Comment by ebugusey** [comment]
> You mean FireFox's internal password manager?
Yes.

**Comment by hrobertson** [comment]
Same issue with FreeIPA. Also the login form is not even detected on page load - I have to right click the input and 'Find matching logins'.
Dispatching an 'input' event from both the username and password input elements does the trick.

There is a demo instance of FreeIPA here that you can test with: https://ipa.demo1.freeipa.org/ipa/ui/

**Comment by hackel** [comment]
This is becoming a pretty severe usability limitation.  I can usually get around it by entering each field and doing a space/backspace before trying to submit the form, but it is a bit obnoxious.  More and more sites are going to be doing this moving forward, I believe.  The fix seems to be so simple...after filling any input field, just send a change event:
`element.dispatchEvent(new UIEvent('change', {view: window, bubbles: true, cancelable: true}));`
In my mind, the aim should be to make it indistinguishable (to the site) from a user typing in the username and password themselves.

**Comment by dlech** [comment]
Does your edit mean that you have actually tested this and it works? If so, can you send a pull request?

**Comment by hackel** [comment]
@dlech Yeah, I am running with that change now and haven't noticed any issues.  Just wanted to get some other eyes on it.  Sorry for not seeing this sooner, I'll submit a PR now.

**Comment by bdurrer** [comment]
What holds PR #739 back? IMO it's the solution to at least 3 open issues. This is a growing problem, since more and more angular/react apps are going online every day.

**Comment by hrobertson** [comment]
Appears to just be the trailing spaces cleanup being in the same commit.
@luckyrat I think your input would be appreciated here.

**Comment by DanCech** [comment]
If the issue is just reviewing the diff, you can view it with the whitespace-only changes ignored by appending `?w=1` to the diff url like: https://github.com/kee-org/KeeFox/pull/739/files?w=1

**Comment by bdurrer** [comment]
I'm happy to report back that the implemented solution is working well.
Thanks everyone involved!

**Comment by Contik** [comment]
Confirmed, in general it's working for sites that previously had problems. Can't get it to work at accounts.google.com/signin in particular but since other sites work well now, I'm guessing that's more of a peculiarity of Google and not so much of KeeFox.

**Comment by hrobertson** [comment]
Confirmed working for FreeIPA (http://www.freeipa.org/page/Demo)
