### ISSUE TITLE
Timer.jsm errors in console

### ISSUE THREAD

**Issue by ShadowSingularity** [kee-org/KeeFox#639]
Been getting alot of errors as i keep on browsing, not sure if something is wrong or i should just ignore them?

http://i.imgur.com/FCzic4c.jpg

Using the most recent version of both KeePass and KeeFox.

**Comment by dlech** [comment]
It this in Firefox, Thuderbird or both?

**Comment by ShadowSingularity** [comment]
Firefox (actually Waterfox if it matters)

**Comment by dlech** [comment]
What Firefox version is Waterfox based on?

I was seeing a similar error in Thunderbird 38, but it seemed to go away after #643. This would have no effect on Firefox/Waterfox though.

**Comment by ShadowSingularity** [comment]
based on v44, recompiled for 64-bit afaik

**Comment by dlech** [comment]
I'm not seeing this in Firefox 45 with KeeFox 1.6.0b3.

**Comment by ShadowSingularity** [comment]
he usually releases around a week after firefox releases, ill wait for the v45 and see if the errors still show, ill get back to you none the less

thanks for your time :+1:
