### ISSUE TITLE
Cannot install (or update to) KeeFox 1.6 / KeePassRPC Plugin without admin password

### ISSUE THREAD

**Issue by polarvogel** [kee-org/KeeFox#649]
I used KeeFox 1.5 for a while on my company pc by installing it without administrator privileges to a custom folder (that I have read / write access to). 

The update or new install for KeeFox 1.6 fails, because KeePassRPCCopiere.exe always requests an administrator password, which I do not have access to.

I went back to my previous v1.5 installation.

**Comment by DaanS** [comment]
I'm having the same issue, even when selecting the second option on the upgrade page.

**Comment by dlech** [comment]
If you have write privileges to the directory where KeePass.exe is located, the follow the [manual installation instructions](https://github.com/luckyrat/KeeFox/wiki/en-|-Getting-started#manual-installation)
