### ISSUE TITLE
Doesn't seem to work with Tor Browser

### ISSUE THREAD

**Issue by space-potato** [kee-org/KeeFox#659]
Hi,

I'm trying to install keefox on tor without success. 
When I first install it, I select the folder where it has to find keepass (portable). Then KeeFox successfully creates the "keepassrpc" file under the keepass folder and it is listed in the plugin list under tools/plugins.

Then it doesn't prompt the password to link the plugin with keepass and I only see the "Launch Keepass" button in the browser. 

I successfully used keefox with both firefox and icecat on this same machine, and I've removed every trace of old installs just to be sure. So I don't think there's something wrong with what I am doing rather than to be a browser issue

If I may add another extra thing: could it be possible to remove the automatic install of keepass? Sometimes it only makes confusion. Or maybe when someone clicks on "setup keefox" for the first time, prompt the user a message where it asks to select the folder on which keepass is installed or choose to download and install the latest version from internet. It should be more user friendly imo

**Comment by MaskChaos** [comment]
I have the same problem, it might because I use the "obf4" network bridge. How can I solve this problem?

**Comment by roflrumps** [comment]
I haven't dug into KeePassRPC, but the source issue may be Tor not supporting connections to localhost and TBB routes all traffic through Tor.  (Given TBB's stance on [preventing non-Tor connections](https://www.torproject.org/projects/torbrowser/design/#security) and [restricting plugin behavior](https://www.torproject.org/projects/torbrowser/design/#philosophy), I doubt there's a simple way around this problem.)

And for the point about avoid unnecessary keepass download, I think #666 covers that.

**Comment by winter20161** [comment]
hi, perhaps my answer in [issue#610](https://github.com/luckyrat/KeeFox/issues/610) would help.
