### ISSUE TITLE
KeeFox connection to Keepass not working after update

### ISSUE THREAD

**Issue by reisenmachtfreude** [kee-org/KeeFox#660]
HI there,

today I got the firefox update to version 46.0.1 (64Bit on Windows). After that the keefox symbol stays gray after lunching keepass using the keefox symbol. (Keepass application starts correctly). 

After that I've upgraded keepass itself to version 2.33. Sadly the connection is still not working. Keefox says I'm not connected to the database.

The version of the Keefox plugin is 1.6.0.

The keefox log:

```
Tue May 10 2016 05:59:27 GMT+0200:DEBUG: KeeFox loaded into a frame/tab/browser
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: _onTabSelected.
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: panel showSearchResults started
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: Removing all matched logins
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: setupButton_ready start
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: Setting widget status
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: setupButton_ready end
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onStateChange keefox_tab: 983041
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onLocationChange keefox_win: 0
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onLocationChange keefox_tab: 0
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onStateChange keefox_tab: 196612
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onStateChange keefox_tab: 720897
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onDOMContentLoaded fired.
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onStateChange keefox_tab: 196612
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: DOMContentLoadedHandler fired.
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onDOMContentLoaded ignored a request (too soon - we're still waiting for the tab to init).
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onDOMContentLoaded fired.
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onLocationChange keefox_win: 1
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onLocationChange keefox_tab: 1
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onStateChange keefox_tab: 131088
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: DOMContentLoadedHandler fired.
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onDOMContentLoaded ignored a request (too soon - we're still waiting for the tab to init).
Tue May 10 2016 05:59:28 GMT+0200:DEBUG: onStateChange keefox_tab: 131088
Tue May 10 2016 05:59:32 GMT+0200:DEBUG: onLocationChange keefox_win: 1
Tue May 10 2016 05:59:32 GMT+0200:DEBUG: onLocationChange keefox_tab: 1
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: Websocket connection error
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: Websocket connection error end
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: Notifying interested observers that the websocket has closed
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: Pausing KeeFox.
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: panel showSearchResults started
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: Removing all matched logins
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: setupButton_ready start
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: Setting widget status
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: setupButton_ready end
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: setAllLogins start
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: setAllLogins end
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: setupButton_ready start
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: Setting widget status
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: setupButton_ready end
Tue May 10 2016 05:59:38 GMT+0200:INFO: KeeFox paused.
Tue May 10 2016 05:59:38 GMT+0200:DEBUG: Websocket connection closed
Tue May 10 2016 05:59:39 GMT+0200:INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 10 2016 05:59:39 GMT+0200:INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 10 2016 05:59:39 GMT+0200:DEBUG: Attempting to connect to RPC server webSocket.
Tue May 10 2016 05:59:39 GMT+0200:DEBUG: Trying to open a webSocket connection
Tue May 10 2016 05:59:49 GMT+0200:DEBUG: onLocationChange keefox_win: 1
Tue May 10 2016 05:59:49 GMT+0200:DEBUG: onLocationChange keefox_tab: 1
Tue May 10 2016 06:00:00 GMT+0200:DEBUG: _onTabSelected.
Tue May 10 2016 06:00:00 GMT+0200:DEBUG: panel showSearchResults started
Tue May 10 2016 06:00:00 GMT+0200:DEBUG: Removing all matched logins
Tue May 10 2016 06:00:00 GMT+0200:DEBUG: setupButton_ready start
Tue May 10 2016 06:00:00 GMT+0200:DEBUG: Setting widget status
Tue May 10 2016 06:00:00 GMT+0200:DEBUG: setupButton_ready end
Tue May 10 2016 06:00:04 GMT+0200:DEBUG: _onTabSelected.
Tue May 10 2016 06:00:04 GMT+0200:DEBUG: panel showSearchResults started
Tue May 10 2016 06:00:04 GMT+0200:DEBUG: Removing all matched logins
Tue May 10 2016 06:00:04 GMT+0200:DEBUG: setupButton_ready start
Tue May 10 2016 06:00:04 GMT+0200:DEBUG: Setting widget status
Tue May 10 2016 06:00:04 GMT+0200:DEBUG: setupButton_ready end
Tue May 10 2016 06:00:15 GMT+0200:DEBUG: onLocationChange keefox_win: 1
Tue May 10 2016 06:00:15 GMT+0200:DEBUG: onLocationChange keefox_tab: 1
Tue May 10 2016 06:00:16 GMT+0200:DEBUG: _onTabSelected.
Tue May 10 2016 06:00:16 GMT+0200:DEBUG: panel showSearchResults started
Tue May 10 2016 06:00:16 GMT+0200:DEBUG: Removing all matched logins
Tue May 10 2016 06:00:16 GMT+0200:DEBUG: setupButton_ready start
Tue May 10 2016 06:00:16 GMT+0200:DEBUG: Setting widget status
Tue May 10 2016 06:00:16 GMT+0200:DEBUG: setupButton_ready end
```

What can I do to fix the problem?

**Comment by crag2012** [comment]
Concur problem report incorrect version for RPC (Have not done a debug)

**Comment by dlech** [comment]
Try clearing the plugin cache. Tools (menu) > Plugins...

![plugins_011](https://cloud.githubusercontent.com/assets/963645/15156181/7c8baf76-16ab-11e6-9b51-758c56500e83.png)

**Comment by reisenmachtfreude** [comment]
Meanwhile I've installed the older KeeFox version 2.23. I wan't to stay with this version because it is supported by my employer.

I've tried the "plugin cache" clear button. Firefox is still not able to connect to Keepass.

In the log file I'm still able to find the "Websocket connection error":
```
Thu May 12 2016 12:58:00 GMT+0200:DEBUG: onStateChange keefox_tab: 983041
Thu May 12 2016 12:58:00 GMT+0200:DEBUG: onLocationChange keefox_win: 0
Thu May 12 2016 12:58:00 GMT+0200:DEBUG: panel showSearchResults started
Thu May 12 2016 12:58:00 GMT+0200:DEBUG: Removing all matched logins
Thu May 12 2016 12:58:00 GMT+0200:DEBUG: setupButton_ready start
Thu May 12 2016 12:58:00 GMT+0200:DEBUG: Setting widget status
Thu May 12 2016 12:58:01 GMT+0200:DEBUG: setupButton_ready end
Thu May 12 2016 12:58:01 GMT+0200:DEBUG: onLocationChange keefox_tab: 0
Thu May 12 2016 12:58:01 GMT+0200:DEBUG: Location changed. A tab is expecting a page load to occur very soon. 
Thu May 12 2016 12:58:01 GMT+0200:DEBUG: onStateChange keefox_tab: 196612
Thu May 12 2016 12:58:01 GMT+0200:DEBUG: onStateChange keefox_tab: 131088
Thu May 12 2016 12:58:04 GMT+0200:DEBUG: _onTabSelected.
Thu May 12 2016 12:58:04 GMT+0200:DEBUG: panel showSearchResults started
Thu May 12 2016 12:58:04 GMT+0200:DEBUG: Removing all matched logins
Thu May 12 2016 12:58:04 GMT+0200:DEBUG: setupButton_ready start
Thu May 12 2016 12:58:04 GMT+0200:DEBUG: Setting widget status
Thu May 12 2016 12:58:04 GMT+0200:DEBUG: setupButton_ready end
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Websocket connection error
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Websocket connection error end
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Notifying interested observers that the websocket has closed
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Pausing KeeFox.
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: panel showSearchResults started
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Removing all matched logins
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: setupButton_ready start
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Setting widget status
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: setupButton_ready end
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: setAllLogins start
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: setAllLogins end
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: setupButton_ready start
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Setting widget status
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: setupButton_ready end
Thu May 12 2016 12:58:05 GMT+0200:INFO: KeeFox paused.
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Websocket connection closed
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Speculatively trying to open a webSocket connection
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Attempting to connect to RPC server webSocket.
Thu May 12 2016 12:58:05 GMT+0200:DEBUG: Trying to open a webSocket connection
```

See screenshot of currently installed plugins:
![plugins](https://cloud.githubusercontent.com/assets/13700219/15212435/dece9f22-1840-11e6-9ac1-5f66666925ed.PNG)

See screenshot of update screen:
![update](https://cloud.githubusercontent.com/assets/13700219/15212458/010d768a-1841-11e6-9fcb-7891c207077a.PNG)

**Comment by Jsavga** [comment]
I'm having the same issue only with Ubuntu. It started when it Ubuntu upgraded from 15.10 to 16.04 LTS. I've followed instructions in https://github.com/luckyrat/KeeFox/issues/657 and https://github.com/luckyrat/KeeFox/issues/648 along with this post and made sure all the mono files and libraries are installed.

The issue I have is the same as this bug in that I have a grayed out Keefox icon. If I click it, I can enter my password and Keepass opens with the correct database but the Keefox icon stays grayed out. 

Below is my debug log:


`Tue May 17 2016 19:52:40 GMT-0400 (EDT):Logging system initialised at Tue May 17 2016 19:52:40 GMT-0400 (EDT)
Tue May 17 2016 19:52:40 GMT-0400 (EDT):DEBUG: registering: chrome://keefox/locale/keefox.properties
Tue May 17 2016 19:52:40 GMT-0400 (EDT):INFO: KeeFox initialising
Tue May 17 2016 19:52:40 GMT-0400 (EDT):DEBUG: Creating a reconnection timer.
Tue May 17 2016 19:52:40 GMT-0400 (EDT):INFO: KeeFox initialised OK although the connection to KeePass may not be established just yet...
Tue May 17 2016 19:52:40 GMT-0400 (EDT):DEBUG: Loading configuration
Tue May 17 2016 19:52:40 GMT-0400 (EDT):DEBUG: Loading commands
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: handleEvent: got event load
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: it's the right window
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: Attaching keyboard listener
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: Didn't find KeeFox widget
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: onBeforeCreated KeeFox widget called
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: Injected KeeFox panel
Tue May 17 2016 19:52:41 GMT-0400 (EDT):INFO: Created KeeFox widget
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: setupButton_ready start
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: Setting widget status
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: setupButton_ready end
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: KeeFox widget instance found
Tue May 17 2016 19:52:41 GMT-0400 (EDT):INFO: Testing to see if we've already established whether KeePassRPC is connected.
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: registering: chrome://keefox/locale/keefox.properties
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: registering: chrome://keefox/locale/FAMS.keefox.properties
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: KeeFox loaded into a frame/tab/browser
Tue May 17 2016 19:52:41 GMT-0400 (EDT):DEBUG: KeeFox loaded into a frame/tab/browser
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 983041
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: onLocationChange keefox_win: 0
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: panel showSearchResults started
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: Removing all matched logins
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: setupButton_ready start
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: Setting widget status
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: setupButton_ready end
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: onLocationChange keefox_tab: 0
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: Location changed. A tab is expecting a page load to occur very soon. 
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 196612
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: Speculatively trying to open a webSocket connection
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: Attempting to connect to RPC server webSocket.
Tue May 17 2016 19:52:42 GMT-0400 (EDT):DEBUG: Trying to open a webSocket connection
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: onDOMContentLoaded fired.
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: DOMContentLoadedHandler fired.
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: onDOMContentLoaded accepted a request.
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: Database is open: false
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: Websocket connection error
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: Websocket connection error end
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: Notifying interested observers that the websocket has closed
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: Pausing KeeFox.
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: panel showSearchResults started
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: Removing all matched logins
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: setupButton_ready start
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: Setting widget status
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: setupButton_ready end
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: setAllLogins start
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: setAllLogins end
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: setupButton_ready start
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: Setting widget status
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: setupButton_ready end
Tue May 17 2016 19:52:43 GMT-0400 (EDT):INFO: KeeFox paused.
Tue May 17 2016 19:52:43 GMT-0400 (EDT):DEBUG: Websocket connection closed
Tue May 17 2016 19:52:44 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 720897
Tue May 17 2016 19:52:44 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 131088
Tue May 17 2016 19:52:44 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 720897
Tue May 17 2016 19:52:44 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 196612
Tue May 17 2016 19:52:44 GMT-0400 (EDT):DEBUG: got sessionstore-windows-restored
Tue May 17 2016 19:52:44 GMT-0400 (EDT):DEBUG: HTTP connection refused. Will not attempt web socket connection.
Tue May 17 2016 19:52:45 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 720897
Tue May 17 2016 19:52:46 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 196612
Tue May 17 2016 19:52:46 GMT-0400 (EDT):DEBUG: onDOMContentLoaded fired.
Tue May 17 2016 19:52:46 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 131088
Tue May 17 2016 19:52:46 GMT-0400 (EDT):DEBUG: DOMContentLoadedHandler fired.
Tue May 17 2016 19:52:46 GMT-0400 (EDT):DEBUG: onDOMContentLoaded accepted a request.
Tue May 17 2016 19:52:46 GMT-0400 (EDT):DEBUG: Database is open: false
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: HTTP connection refused. Will not attempt web socket connection.
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: Metrics startup for KeeFox version: 1.6.0
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: onDOMContentLoaded fired.
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 131088
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: onStateChange keefox_tab: 131088
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: DOMContentLoadedHandler fired.
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: onDOMContentLoaded accepted a request.
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: Database is open: false
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: calculatePreviousSessionMetrics finished
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: Started a metrics session.
Tue May 17 2016 19:52:47 GMT-0400 (EDT):DEBUG: resetAggregates started
Tue May 17 2016 19:52:48 GMT-0400 (EDT):DEBUG: resetAggregates finished
Tue May 17 2016 19:52:48 GMT-0400 (EDT):DEBUG: Creating a metrics timer.
Tue May 17 2016 19:52:50 GMT-0400 (EDT):INFO: About to execute: /usr/bin/mono /usr/lib/keepass2/KeePass.exe -KeePassRPCWebSocketPort:12546 -iocredfromrecent /home/jsavga/Documents/KeePass/JamesFireFox.kdbx
Tue May 17 2016 19:52:50 GMT-0400 (EDT):DEBUG: HTTP connection refused. Will not attempt web socket connection.
Tue May 17 2016 19:53:03 GMT-0400 (EDT):DEBUG: metrics being sent
Tue May 17 2016 19:53:12 GMT-0400 (EDT):DEBUG: handleEvent: got event unload
Tue May 17 2016 19:53:12 GMT-0400 (EDT):DEBUG: it's the right window
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: Window shutting down...
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: Window shut down.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:12 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Tue May 17 2016 19:53:13 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Tue May 17 2016 19:53:13 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.`

**Comment by docbill** [comment]
Same issue.  I've tried about everything...  No luck.

**Comment by luckyrat** [comment]
For any of you on Linux, make sure you've got the latest and complete mono package installed.

Otherwise, try all the steps in the relevant section in the troubleshooting guide: https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting#keefox-panel-has-a-launch-keepass-button

And then please supply a KeePassRPC log if you still have no luck: https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting#debug-the-problem

**Comment by nailyk-fr** [comment]
Maybe it can help some of you: 

I was experiencing the same issue (debian 8, keepass portable 2.34). 
My keepass portable is installed in : 

> ~/.keepass2.34/

and i also had the distribution package in 

> /usr/lib/keepass2/

When i cp the plugin in  ~/.keepass2.34/plugins it load fine in keepass but connection with keefox doesn't work with the 'HTTP not refused'. 
Someone in another issue mention plugins folder problem so I cp the plugin in 

> /usr/lib/keepass2/plugins

clear cache and then everything is fine. 
Hope it can be helpful.
