### ISSUE TITLE
Keefox contantly asks for authorizing new connections

### ISSUE THREAD

**Issue by vasyugan** [kee-org/KeeFox#664]
It seems each time I start firefox and each time my laptop resumes from suspend, keefox wants me to authorize a new connection. Connection security is unchanged at "medium", when I look at the "authorized clients" tab, I find a single entry there for my firefox, valid until 2017/05/19.
Right now I saw 25 black windows entitled "authorize new client" which didn't respond to any attempt to interact with them. I'm seeing this on two laptops running Arch Linux, 
Versions: 
Keepass: 2.32
Keefox: 1.6.0
KeepassRPC: 1.6.0.0
Firefox: 46.0.1

**Comment by luckyrat** [comment]
Does this only happen when KeePass is open and KeeFox connected to it when the laptop goes to sleep?

Does your KeePass automatically lock when the laptop sleeps?

**Comment by vasyugan** [comment]
I think this is the scenario where it happens, but I would have to observe whether it _only happens in these situations. I am on Linux, using the MATE desktop. The screen is locked upon resume, yes.

**Comment by vasyugan** [comment]
Now I get the authorization dialogue each time I change the network interface, that is, when switching from Wifi to cable (using dhcp client identifier I ensure that I receive the same IP address, regardless whether the connection is wireless or wired.)
