### ISSUE TITLE
Login form not detected at http://np.ironhelmet.com/

### ISSUE THREAD

**Issue by contre** [kee-org/KeeFox#667]
When visiting http://np.ironhelmet.com, KeeFox does not detect a login form as as such does not offer to store the password.

KeeFox 1.60
Firefox 46.0.1 64-bit
KeePass 2.33

**Comment by freeasinbear** [comment]
How has it been written the URL on KeePass? Lately I'm finding that if the URLs are not perfectly matched they won't show up

**Comment by contre** [comment]
To clarify, it doesn't detect the login form when I first enter credentials on the site and ask if I want to create an entry.
