### ISSUE TITLE
authorization window close too quickly

### ISSUE THREAD

**Issue by Cybereric** [kee-org/KeeFox#673]
Hello,
I've a problem with the "authorization window" (where the authorization code is written in red)
It appears and stay open less than one second. Then the form window appear but I can't type anything
because I've just seen half of the code or less :-/
I use :
Firefox 46.01
Keefox 1.6
Keepass 2.33
Ubuntu 14.04 LTS

**Comment by chronometric** [comment]
I agree with the premise, though mine stays open a good 30 seconds. It usually closes right around when I'm done typing in my password, so at that point I rush to select and copy the auth code to paste into the KeeFox dialog. 

I'm not sure what action is used to determine this window should close, but it should either be a different one, it should be on a timer, or simply remain open until the user closes it..
