### ISSUE TITLE
Website not detecting KeeFox input

### ISSUE THREAD

**Issue by FaBjE** [kee-org/KeeFox#678]
I have an issue on the website https://jouw.postnl.nl/ (Dutch postal service)

KeeFox does a fine job finding the login and entering it into the right fields, but when I want to submit the form the website refuses because it claims there is no data entered. This is the case though. I can see it having the right values.

When adding a random character and removing it with "backspace" the website sees the input field as "filled" and I can submit the form when I do this for both the email and password field.

They are probably listing to some "onkeypress" event or something to determine if data was entered and I guess KeeFox enters it trough DOM access, not triggering the event.

But I might be wrong.
I remember having the same issues on some other website but I forgot which one it was.

Is there any way to get KeeFox to "fake" typing so (dodgy) websites register the input?

**Comment by roflrumps** [comment]
#638 and #578 seem to cover this.  There doesn't seem to be a workaround currently.

**Comment by FaBjE** [comment]
Thanks for the heads-up roflrumps, it is indeed a duplicate of #638 and #578
