### ISSUE TITLE
Documentation missing: Location Manager via the “Edit Group” KeePass feature

### ISSUE THREAD

**Issue by AJGranowski** [kee-org/KeeFox#682]
**KeePass version:** 2.34
**KeeFox version:** 1.6.0.0

I can't seem to find any documentation as to how the Location Manager feature is supposed to work.

The Location Manager can be found by clicking "Edit Group" on an existing KeePass group, clicking the "KeeFox" tab in the new dialog window, clicking the combo-box that says "Anywhere" and selecting "Location manager..." from the drop-down menu.

So far, all I've found officially mentioning it is [this release note for KeeFox 0.8.10](http://keefox.org/news/detail/2011/03/21/keefox-0810-released/) when it was listed as a new feature. Verbatim, it says:

> A new “location manager” and an ability to set different home groups for different locations via the “edit group” KeePass feature

Doing some digging, the feature is mentioned in [this issue](https://github.com/luckyrat/KeeFox/issues/58#issuecomment-12187005), and there is some interesting related source code [here](../blob/master/KeePassRPC/Forms/KeeFoxGroupUserControl.cs#L155-L204), but the end result is that I'm still confused with what this feature actually is.
## Issue Goals:
- [ ] What does this feature do? (And if applicable, in what case?)
- [ ] Why would I use/want to use this feature?
- [ ] How is this feature meant to be used (with examples)?
- [ ] Write documentation of the answers to the preceding questions.

**Comment by luckyrat** [comment]
It is to help configure different home groups for different computers accessing the same password database. E.g. one for home and one for work. Set the location field in the KeeFox options dialog and configure the home group in KeePass accordingly by using the location manager.

In theory it could be used for other configuration differences too but I've never got around to it; I'm considering whether it's really worth keeping this feature around in the long-term but don't currently have plans for its imminent removal.
