### ISSUE TITLE
User interaction needed to enable login/submit button [Eg: Topcoder community login]

### ISSUE THREAD

**Issue by snugghash** [kee-org/KeeFox#690]
The [login page of topcoder](https://www.topcoder.com/login/) has a login button which only activates when some keystrokes are pressed in both the fields.
The auto-fill provided by KeeFox doesn't work, we need to type/paste at least one letter.
I haven't explored this fully, but it _is_ frustrating.

Now, KeeFox isn't fully responsible for providing a solution for some bad website UX, but I feel there can be some easy solution for this; and given the project's experience in the the area, are there any ideas?

Of course, if this is proves to be a worthwhile, fixable bug, I can try my hand at contributing the patch.

**Comment by Larusek** [comment]
Same thing happens with very popular (like ebay) polish site Allegro https://ssl.allegro.pl/login/auth
You need to manually add or remove at least one sign to activate the login button. It is frustrating. It would be awesome to have it fixed.
