### ISSUE TITLE
Pop-ups from KeePass don't close automatically

### ISSUE THREAD

**Issue by snugghash** [kee-org/KeeFox#691]
The Chrome and Firefox default password managers close the pop-ups upon user interaction elsewhere, and still provide the option to interact with it later. 

Is it too much work to be worthwhile to implement this UX in KeeFox?

**Comment by sergeevabc** [comment]
Not sure if this is, but I am sick and tired of closing KeeFox’s layers by clicking “Close” button instead of clicking elsewhere on the page. This should be a fix to implement, please do.

![](https://images.vfl.ru/ii/1544614193/2ff1954a/24570938.png)
