### ISSUE TITLE
Sync site-specific settings with Firefox Sync

### ISSUE THREAD

**Issue by Ian2020** [kee-org/KeeFox#693]
Mozilla's wiki ["Services/Sync/Addon Sync" (mozilla.org)](https://wiki.mozilla.org/Services/Sync/Addon_Sync) suggests it's possible for add-ons to synchronise their settings across a users' browser instances. It would be very useful if the site-specific settings could be synched in this way. From the link:

> Are Add-on Settings Synchronized?
> 
> Maybe. Currently, add-on sync leaves setting synchronization to the individual add-on. If an add-on has support for syncing settings, they will be synced. If not, they won't. For now, if an add-on doesn't preserve settings during Sync, you should contact the add-on's author and request Sync support.
> 
> For add-on authors, to sync settings using Sync, there are effectively 3 methods.
> 1. Synchronize preferences (see https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Firefox_Sync/Syncing_custom_preferences)
> 2. Build a Sync engine (if you need to sync more than just preferences). If you need this, please drop by the #sync channel in IRC so you can chat with a Sync developer (there are some important details not currently captured formally in any docs).
> 3. Build it yourself, not using Sync.
> 
> We recognize that having all add-on settings magically synchronize would be a useful feature. We are exploring options for facilitating this. Unfortunately, nothing made the first cut for add-on sync.

**Comment by chronometric** [comment]
Site-specific settings? In the context, do you mean the login info? Because FF already has an in-built and completely insecure login saver. Somehow he task of building enterprise-level security into the FF sync and login system, and somehow ensuring that the external KeePass program will run at the next sync location, seem to evaporate the plugin and subsume those functions back into FF. Apologies if you were thinking along other lines; adding the entire (encrypted) keepass kdbx file into the FF sync could actually be really handy.

**Comment by Ian2020** [comment]
Hi, sorry  should have been more clear - I mean all the settings stored under Keefox->Options->Finding Entries->"Site-specific settings".  So if I have had to add "https://github.com/" because it has an unusual username field name this setting will be available on all my browsers.

**Comment by chronometric** [comment]
Mmmm, I see what you mean. That's not a bad idea, but storing KeePass info in the Firefox sync seems like an inelegant solution.

I think you might do much better to look at the KeePass sync options, native and through plugins. You share the full KeePass database between devices, so the only limits are what KeePass can do on the next device you're using. 

For instance, if you sync it (or simply access a "cloud" version of your database") on a full computer at work, and configure KeePass with KeeFox and all the other same plugins, it should behave just the same. However, your smartphone plugin might not recognize the auto-type features (though Keepass2Android supposedly can), or maybe another OS port is not advanced enough to use the KeeFox plugins? 

My experience isn't that wide, but the KeePass cloud/sync system is fairly intuitive, rich, and compatible across many devices and plugins, so I would exhaust those possibilities before trying to fold KeePass into the Firefox sync, as convenient as that may ultimately be. Just my thoughts...it would take a lot of work to separate out the non-sensitive info from your database (and would be arguable what fields this constitutes...sometimes clues can be just as damaging as a password or login itself).

**Comment by Ian2020** [comment]
I think you're right, it would be better if these site-specific settings were in the KeePass database itself rather then stored as config of the browser plugin. Then they would be available across all devices if using cloud sync as you suggest.

**Comment by jdunn0** [comment]
If the only site specific settings you need are form names, you can already store that per-entry in KeePass when the KeeFox plugin is installed.
Just open the "Edit Entry" dialog for a site in KeePass, select the KeeFox tab and then select the "Form Fields" tab.
There you will see two entries for Username and Password which you can double click to edit and specify the names and/or ids used by the login form on the site for that entry.
You can also add an entry for other form elements like a "Remember Me" check box for site to always make it not checked or checked.

**Comment by Ian2020** [comment]
Thanks - I have tried this but find that I still need the site-specific settings before the per-entry ones can take effect. i.e. if there's a website with a login box named "uid" I need to add this to both the site-specific settings for that site AND the per-entry form fields before any entries are found.
