### ISSUE TITLE
Any way to force reauthorization? Medium security isn't requesting auth to Keepass, but high security does OK.

### ISSUE THREAD

**Issue by numericOverflow** [kee-org/KeeFox#694]
Is there any way to force Keefox to re-authorize to Keepass when using medium security level?  When I switch to high security in Keefox, it immediately attempts to connect and presents a popup for authorization.  However, it isn't presenting a dialog when I am on medium security.  I've revoked all keys from within KeepassRPC, but can't figure out how to kick-start Keefox into initiating the authorization process whenever it's set to medium security.  Restarting FireFox hasn't kicked the reauth, nor has going through the upgrade or install screens as suggested in the help docs.

It's able to connect, but for some reason won't initiate the connection when I'm on medium security.  I've fought with similar issues in the past where KFox just won't reauth, but once it does, everything is fine.  Is there any about:config entry to delete/reset or another way to trigger KeeFox to reach out to KeepassRPC, or an 

Window7 x64
Firefox Developer version (49.0a2 (2016-08-01))
Keepass 2.34
KeepassRPC 1.6.0.0
KeeFox 1.6.0

**Comment by jjohns71** [comment]
I am curious about this and having the same issue, my database keefox was linked to get deleted and restored and it won't reauthorize keefox with keepass so even with keepass open, keefox will not connect. Forcing security mode into 'high' establishes a connection for that session but if I switch back to 'medium' keefox can not find keepass again. Is there any way to do a completely fresh install? I've tried removing the extension, and deleting the plugin from the keepass directory but for whatever reason I can not get keefox to establish a connection to the new database location on 'Medium' security settings.
