### ISSUE TITLE
Request: Update "Last Access Time"

### ISSUE THREAD

**Issue by DocMAX** [kee-org/KeeFox#701]
Hello,

not sure where to put my request. But i start here.

Can you please make KeeFox update the (hidden) "Last Access Time"-column, whenever i access a password from KeeFox?

THANK YOU!
DocMAX

**Comment by Aryol57** [comment]
...coolll...@`A`A`

**Comment by Aryol57** [comment]
[0ac53f2870d42d8c31e31eb0bb28f456 (1).pdf](https://github.com/luckyrat/KeeFox/files/445190/0ac53f2870d42d8c31e31eb0bb28f456.1.pdf)

**Comment by DocMAX** [comment]
What?
