### ISSUE TITLE
Using form fields reserved for internal use (eBay)

### ISSUE THREAD

**Issue by daniel-barrows** [kee-org/KeeFox#702]
This is a feature request.
I would like to be able to manually edit form fields to use KeeFox reserved fields.
For example, I want to be able to open the KeePass "Edit Entry" Dialog, click on the KeeFox tab, then edit a particular field entry. This is currently possible. Currently, when I enter as a field value {USERNAME}, I get an error message, saying "Please change the value of this form field - it is currently set to a value that KeeFox needs reserved for internal use." I would like KeeFox instead to actually replace {USERNAME} with its internally reserved value, the username.
I came across this in the [eBay login](https://signin.ebay.com/ws/eBayISAPI.dll?SignIn), which uses a user-visible username entry, as well as a hidden username entry. Only the hidden entry is actually necessary, but it would be nice to have the entry box actually show the username to the user when it is automatically filled (by populating the user-visible entry as well as the hidden entry).

**Comment by apelly** [comment]
The user visible entry appears to change its ID randomly too. It might be better to have options other than name and id for field selection, placeholder for instance, is always the same for the visible  ebay username
