### ISSUE TITLE
Keefox 1.6.3 disables Multiprocess Windows on Firefox 49.0b8 (e10s)

### ISSUE THREAD

**Issue by forge33** [kee-org/KeeFox#703]
Decided to try e10s in hope that experience would be better then the current 64bit version
Started with all addons disabled,
Turned on Ad-block plus, no problem
Turned on keefox, Multiprocess windows gets disabled. Disable it, Multiprocess windows gets enabled.
Uninstall and reinstall keefox 1.6.3, same thing.

**Comment by luckyrat** [comment]
This might be related to a Firefox bug regarding the way that e10s gets disabled when add-ons are installed/enabled. I thought I read that they have fixed it now but maybe it hasn't made it to v49 (yet?)

For most users, e10s should be automatically disabled when any add-on is installed.

When manually enabling e10s in dev/nightly Firefox builds I've not seen any problem with KeeFox and e10s compatibility so far.

Can you manually enable e10s after the KeeFox installation and subsequent Firefox restart has caused it to become disabled again?

**Comment by forge33** [comment]
It's already enabled 

browser.tabs.remote.autostart already set to true
browser.tabs.remote.force-enable doesn't exist anymore

however it seems that firefox is only allowing selected addons to be enabled
http://arewee10syet.com/ Keefox is listed as compatible

However
https://blog.mozilla.org/futurereleases/2016/08/02/whats-next-for-multi-process-firefox/

**Comment by austinried** [comment]
Same thing here, enabling KeeFox 1.6.3 on FF 49.0.2 disables multiprocess with a "disabled by addons" message.
