### ISSUE TITLE
Keefox in Firefox 49.0.1 can't launch Keepass with relative path

### ISSUE THREAD

**Issue by Fossius** [kee-org/KeeFox#708]
The path is: `.\Profiles\extensions\KeePass` With ff 47 and earlier work fine. I'm using portable firefox based on pcx firefox. Here you can try it [firefox 47](https://yadi.sk/d/t5OuTTH7sk5oN) and [firefox 49](https://yadi.sk/d/XLSR3LxGvexLi), don't worry - no viruses :)

**Comment by mrxanto** [comment]
Is there any chance that this problem will be fixed?
