### ISSUE TITLE
https://login.live.com/ does not detect that the fields are filled

### ISSUE THREAD

**Issue by zuim** [kee-org/KeeFox#714]
When I try to login at microsoft (https://login.live.com/) I get a message saying:

> Please enter your phone number or your email address in the format someone@example.com.
> and
> Please enter the password for your Microsoft account.

This can be fixed by manually typing a letter in the boxes.

Maybe there could be an option to simulate typing or you could fire all javascript typing events after filling the field.

**Comment by zuim** [comment]
This also happens with paypal.

**Comment by guile0** [comment]
I cannot logon with autofill to login.live.com either. I have to delete the last char and type it again.
Another problem : there is a page with the login field, then another page for the password field. Keefox cannot handle that because it tries to type the login and the password in the same page.
