### ISSUE TITLE
Incompatible KeePassRPC.plgx on Linunx DEB Family

### ISSUE THREAD

**Issue by KRUXLEX** [kee-org/KeeFox#716]
On my distribution I was see from few weeks issue with Plugin for KeeFox.
Always after open KeePass I see alert: Plugin is incompatible with program version: /usr/lib/KeePas2/Plugin/KeePassRPC.plgx
Try to find a correct plugin on this webside.
https://s14.postimg.org/5wpo9y9i9/Zrzut_ekranu_z_2016_10_15_23_13_46.png

**Comment by dlech** [comment]
You most likely don't have all of the required mono packages installed. Quick fix is `sudo apt-get install mono-complete`.

More info on the wiki: https://github.com/luckyrat/KeeFox/wiki/en-%7C-Installation-%7C-Linux

**Comment by rosa2** [comment]
Thanks @dlech for the solution. It worked :)

**Comment by KRUXLEX** [comment]
Hi, unfortunately I have installed newest version. So must me another solution.
