### ISSUE TITLE
Password generator hangs firefox and KDE for a while

### ISSUE THREAD

**Issue by adocampo** [kee-org/KeeFox#724]
*EDITED* I can reproduce this error on KDE Plasma only. I've just tried on GNOME and i3w and works just fine.

Since a while ago, I'm having troubles with the password generation feature, at first I notized it on a old computer with a old hard disk, but I tried it on several newer, more powerful and faster computers and all of them suffers the same behavior. When I click on "Create new password", browser (and even desktop, but other opened programs works fine) hangs for 25s. 
Mi environments are all Arch Linux 64bits, Plasma Desktop (latest)
Firefox Sync is enabled (syncing all but passwords).
Disabling all addons does not affect this behavior.

**Comment by guraltsev** [comment]
Can confirm! I am Leap 42.2 with plasmashell 5.8.3

**Comment by rezad1393** [comment]
me too

**Comment by julakali** [comment]
confirmed with KDE Frameworks 5.29.0 and firefox 50.1.0.
