### ISSUE TITLE
Ubuntu PPA: incompatible xul-ext-keefox with keepass2-plugin-rpc

### ISSUE THREAD

**Issue by adrianf0** [kee-org/KeeFox#725]
There is incompatibility issue on Ubuntu 16.10 using ppa:dlech/keepass2-plugins.
Version of the keepass2-plugin-rpc: 1.6.2 (from Keepass2 tools->Plugins)
Version of the xul-ext-keefox: 1.6.3 (version of Keefox in Firefox)
The keefox-keepass2 connection works only after clear of the plugin cache and its compilation (restart of the program). Only then, Firefox is able to connect with Keepass2. At this stage, restart of either Firefox or Keepass2 will result permanent connection failure (gray Keefox icon in Firefox) --- although the port is open on Keepass2 side (checked with: telnet localhost 12546).

**Comment by dlech** [comment]
What is the output of this command?

    dpkg -s keepass2-plugin-rpc | grep Version

**Comment by adrianf0** [comment]
> Version: 1.6.3-0

**Comment by adrianf0** [comment]
The plugin installed by  `xul-ext-keefox` works -> it's active in Firefox (49.0.2). For some reason it's not able to connect to `keepass2` which is running and expecting connection of the default port. Although I see some TCP packets being exchanged between the plugin and the program (localhost), the plugin informs that user is not logged in and requests to launch `keepass2`. If I clear cache of the RPC plugin on `keepass2` side, to problem will disappear until restart of Firefox or `keepass2`.
