### ISSUE TITLE
Some Sites, netflix for example, doesn't "accept" the autotyping

### ISSUE THREAD

**Issue by Darksider3** [kee-org/KeeFox#727]
...
"What do you mean with accept autotyping?"

The autotyping feature does his job just fine. On any page, besides Netflix, it works fine.
But in Netflix, not. If i copy the username&password in the fields, it works without problems. Only if KeeFox fills it, it won't accept it.
And with that i mean both username and Password.
How can i fix something like that? It's not like that i need to adjust some textfields or so :/

Sincerely

**Comment by dlech** [comment]
Sounds like #638.
