### ISSUE TITLE
Fields are not filled anymore on Firefox 50 with e10s 

### ISSUE THREAD

**Issue by MIuIddy** [kee-org/KeeFox#729]
The update to Firefox 50 activated e10s on one of my PCs and on that PC KeeFox stopped filling the fields.
Clicking on the KeeFox icon doesn't show any detected accounts either, when it should.

**Comment by dlech** [comment]
Have you tried any of the [troubleshooting tips on the wiki](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting)?

**Comment by MIuIddy** [comment]
There isn't really anything describing my problem.
The RPC plugin is working fine and all my logins are listed in KeeFox under logins.
Manually selecting the login for the sites from the logins doesn't work either.

**Comment by dlech** [comment]
Have you checked the error console? Have you tried enabling debug logging? Is this a problem on all websites or just certain sites?

**Comment by MIuIddy** [comment]
The problem is on all sites. There are no errors in the log.

Here is what the log says:

Starting Firefox:
`Fri Nov 18 2016 17:51:04 GMT+0100:Logging system initialised at Fri Nov 18 2016 17:51:04 GMT+0100
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: registering: chrome://keefox/locale/keefox.properties
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: KeeFox initialising
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: KeePass install location found in preferences: C:\Program Files (x86)\KeePass Password Safe 2\
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: Looking for the KeePass EXE.
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: KeePass EXE found in correct location.
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: KeePassRPC install location inferred.
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: Looking for the KeePassRPC plugin plgx
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: KeePassRPC plgx found in specified or default location.
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: Checking and updating KeePassRPC installation settings
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: KeePass is not running or the connection might be established in a second...
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: Creating a reconnection timer.
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: KeeFox initialised OK although the connection to KeePass may not be established just yet...
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: Loading configuration
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: Loading commands
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: Metrics startup for KeeFox version: 1.6.3
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: handleEvent: got event load
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: it's the right window
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: Attaching keyboard listener
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: Didn't find KeeFox widget
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: onBeforeCreated KeeFox widget called
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: Injected KeeFox panel
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: Created KeeFox widget
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: setupButton_ready start
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: Setting widget status
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: setupButton_ready end
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: KeeFox widget instance found
Fri Nov 18 2016 17:51:04 GMT+0100:INFO: Testing to see if we've already established whether KeePassRPC is connected.
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: registering: chrome://keefox/locale/keefox.properties
Fri Nov 18 2016 17:51:04 GMT+0100:DEBUG: registering: chrome://keefox/locale/FAMS.keefox.properties
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: KeeFox loaded into a frame/tab/browser
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: KeeFox loaded into a frame/tab/browser
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: got sessionstore-windows-restored
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: onLocationChange keefox_tab: 0
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: onStateChange keefox_tab: 196612
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: onDOMContentLoaded fired.
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: onStateChange keefox_tab: 131088
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: calculatePreviousSessionMetrics finished
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: Started a metrics session.
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: resetAggregates started
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: resetAggregates finished
Fri Nov 18 2016 17:51:05 GMT+0100:DEBUG: Creating a metrics timer.
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: onLocationChange keefox_win: 0
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: panel showSearchResults started
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Removing all matched logins
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: setupButton_ready start
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Setting widget status
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: setupButton_ready end
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Speculatively trying to open a webSocket connection
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Attempting to connect to RPC server webSocket.
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Trying to open a webSocket connection
Fri Nov 18 2016 17:51:06 GMT+0100:INFO: Websocket connection opened
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: received message from web socket
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: received message from web socket
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Removing keefox-connection-message notification
Fri Nov 18 2016 17:51:06 GMT+0100:INFO: KeePass install location found in preferences: C:\Program Files (x86)\KeePass Password Safe 2\
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Looking for the KeePass EXE.
Fri Nov 18 2016 17:51:06 GMT+0100:INFO: KeePass EXE found in correct location.
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: KeePassRPC install location inferred.
Fri Nov 18 2016 17:51:06 GMT+0100:INFO: Looking for the KeePassRPC plugin plgx
Fri Nov 18 2016 17:51:06 GMT+0100:INFO: KeePassRPC plgx found in specified or default location.
Fri Nov 18 2016 17:51:06 GMT+0100:INFO: Checking and updating KeePassRPC installation settings
Fri Nov 18 2016 17:51:06 GMT+0100:INFO: KeePass is not running or the connection might be established in a second...
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Observed an event: [xpconnect wrapped (nsISupports, nsIPrefBranch, nsIPrefBranch2)],nsPref:changed,lastConnectedToKeePass
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Request to refresh KeeFox's view of the KeePass database received.
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Sending a JSON-RPC request
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: starting webcrypto encryption
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Refresh of KeeFox's view of the KeePass database initiated.
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Sending a JSON-RPC request
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: starting webcrypto encryption
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: received message from web socket
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: starting webcrypto decryption
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'data prep 1' took: 1
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: received message from web socket
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: starting webcrypto decryption
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'data prep 1' took: 0
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'key hash' took: 2
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'data prep 2' took: 0
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'generate HMAC' took: 0
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'import key' took: 1
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'key hash' took: 2
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'data prep 2' took: 0
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'generate HMAC' took: 1
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'import key' took: 0
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'aes-cbc' took: 1
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'utf-8 conversion' took: 1
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'aes-cbc' took: 1
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: decryption stage 'utf-8 conversion' took: 0
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Refreshing KeeFox's view of the KeePass database.
Fri Nov 18 2016 17:51:06 GMT+0100:INFO: At least one database is open.
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: panel showSearchResults started
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Removing all matched logins
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: setupButton_ready start
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Setting widget status
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: setupButton_ready end
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: setAllLogins start
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: setAllLogins end
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: setupButton_ready start
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: Setting widget status
Fri Nov 18 2016 17:51:06 GMT+0100:DEBUG: setupButton_ready end
Fri Nov 18 2016 17:51:06 GMT+0100:INFO: KeeFox feels very refreshed now.`

Opening a site to log into:
`Fri Nov 18 2016 17:51:20 GMT+0100:DEBUG: metrics being sent
Fri Nov 18 2016 17:51:51 GMT+0100:DEBUG: onLocationChange keefox_win: 0
Fri Nov 18 2016 17:51:51 GMT+0100:DEBUG: panel showSearchResults started
Fri Nov 18 2016 17:51:51 GMT+0100:DEBUG: Removing all matched logins
Fri Nov 18 2016 17:51:51 GMT+0100:DEBUG: setupButton_ready start
Fri Nov 18 2016 17:51:51 GMT+0100:DEBUG: Setting widget status
Fri Nov 18 2016 17:51:51 GMT+0100:DEBUG: setupButton_ready end`

Trying to force login:
`Fri Nov 18 2016 17:52:37 GMT+0100:DEBUG: loading and auto submitting button 0false...
Fri Nov 18 2016 17:52:37 GMT+0100:DEBUG: onLocationChange keefox_win: 0
Fri Nov 18 2016 17:52:37 GMT+0100:DEBUG: panel showSearchResults started
Fri Nov 18 2016 17:52:37 GMT+0100:DEBUG: Removing all matched logins
Fri Nov 18 2016 17:52:37 GMT+0100:DEBUG: setupButton_ready start
Fri Nov 18 2016 17:52:37 GMT+0100:DEBUG: Setting widget status
Fri Nov 18 2016 17:52:37 GMT+0100:DEBUG: setupButton_ready end`

**Comment by Edtcetera** [comment]
I have the same problem on my Firefox 50 Windows machine:
What is not working is auto-completion in pop-up system windows. In previous Firefox versions, websites that ask to authenticate via pop-up system window used to have a 'Launch Keepass' button if KeePass was not logged in, or the fields already filled in. 

All other functionalities seem to be working (authenticate on new install with KeePass, ask me to save new passwords, able to view and edit database).

**Comment by Edtcetera** [comment]
![capture](https://cloud.githubusercontent.com/assets/16753159/20454304/a773a756-adf1-11e6-9147-96f8bac549a8.JPG)

**Comment by moarf56** [comment]
Hi all.

Same problem here ! any idee ?

Thx

**Comment by dlech** [comment]
@Edtcetera, the authentication dialog box not working is issue #709. I don't think this is what the original comment in this issue is referring to. I think this issue is about filling forms on web pages themselves.
