### ISSUE TITLE
Update existing entry (URL, Favicon)

### ISSUE THREAD

**Issue by cypressious** [kee-org/KeeFox#741]
As a new user I have a big database full of entries with little information except for name and user and password. Now that I have this wonderful addon installed, I'd like to enrich the entries in my existing database.

For one, I don't have the URL set for most of my entries which makes it hard enough, to even find them through KeeFox (see #484).

Second, I'd like to have a way to attach a site's favicon to my DB entries. As I see it, KeeFox already can do this for new entries. Would it be possible to do the same for existing entries?

**Comment by dlech** [comment]
There is another KeePass plugin for the favicon. https://sourceforge.net/projects/keepass-favicon/
