### ISSUE TITLE
[REQ] Port KeeFox to chromium based browsers.

### ISSUE THREAD

**Issue by freMea** [kee-org/KeeFox#743]
Hi,
@luckyrat

**KeeFox** is the best and convenient way to manage password and custom string fields between **keepass** and browser. Firefox is changing and the transition is hard for users and extensions dev. I planned to migrate to Vivaldi browser and help them to improve their browser reporting review and issues. But currently, using chrome extension to replace **KeeFox** is not satisfying. **ChromeIPass** seems the best choice out there but not very user friendly to set with custom string fields.

It would be great to see **KeeFox** features ported to chromium based browsers. Maybe you could cooperate with the **ChromeIPass** dev. I wrote about this [here](https://github.com/pfn/passifox/issues/362).

Best regard

**Comment by freMea** [comment]
I eagerly wish to see KeeFox extension and the Chrome store. ❤️
Will you think about it @luckyrat or are you definitely not interested ?

**Comment by dlech** [comment]
https://zohodiscussions.com/keefox/topic/any-chrome-extension-projects-using-keepassrpc
