### ISSUE TITLE
Enter auth data again and again

### ISSUE THREAD

**Issue by m707** [kee-org/KeeFox#748]
I am on:

Windows 8.1, X64
FF 50.1.0
Keepass 2.34
Keefox 1.6.4

Security level is medium, but I have to fill the RPC Auth dialogue each time FF starts. It used to work like a charme for years. Not sure if realy related but I lost my FF profile last summer. After that (I am quite sure problems already started a little earlier) I didn't managed to get it working agian. I already installed/deinstalled everything concerned, but no chance. 
After the auth is successful I see a KPRPC Key in FF passwords settings TAB, however, I do not see anything "Authorised clients" in the keePassRPC tab of KeePass :(.
This is the debug log untill FF is waiting for auth, and Keepass pops up the key.

```
Wed Dec 28 2016 10:30:56 GMT+0100:Logging system initialised at Wed Dec 28 2016 10:30:56 GMT+0100
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: registering: chrome://keefox/locale/keefox.properties
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: KeeFox initialising
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: KeePass install location found in preferences: C:\Program Files (x86)\KeePass Password Safe 2\
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: Looking for the KeePass EXE.
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: KeePass EXE found in correct location.
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: KeePassRPC install location inferred.
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: Looking for the KeePassRPC plugin plgx
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: KeePassRPC plgx found in specified or default location.
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: Checking and updating KeePassRPC installation settings
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: KeePass is not running or the connection might be established in a second...
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: Creating a reconnection timer.
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: KeeFox initialised OK although the connection to KeePass may not be established just yet...
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: Loading configuration
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: Loading commands
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: Metrics startup for KeeFox version: 1.6.4
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: handleEvent: got event load
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: it's the right window
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: Attaching keyboard listener
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: Didn't find KeeFox widget
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: onBeforeCreated KeeFox widget called
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: Injected KeeFox panel
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: Created KeeFox widget
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: setupButton_ready start
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: Setting widget status
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: setupButton_ready end
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: KeeFox widget instance found
Wed Dec 28 2016 10:30:56 GMT+0100:INFO: Testing to see if we've already established whether KeePassRPC is connected.
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: registering: chrome://keefox/locale/keefox.properties
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: registering: chrome://keefox/locale/FAMS.keefox.properties
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: KeeFox loaded into a frame/tab/browser
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: KeeFox loaded into a frame/tab/browser
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: KeeFox loaded into a frame/tab/browser
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: got sessionstore-windows-restored
Wed Dec 28 2016 10:30:56 GMT+0100:DEBUG: onStateChange keefox_tab: 983041
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Speculatively trying to open a webSocket connection
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: prepareFill accepted
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Attempting to connect to RPC server webSocket.
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Trying to open a webSocket connection
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: calculatePreviousSessionMetrics finished
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Started a metrics session.
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: resetAggregates started
Wed Dec 28 2016 10:30:58 GMT+0100:INFO: Websocket connection opened
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: received message from web socket
Wed Dec 28 2016 10:30:58 GMT+0100:WARN: KeeFox wurde die Verbindung nicht erlaubt, wahrscheinlich weil das eingegebene Verbindungspasswort falsch ist. Weitere Informationen werden folgen: Stored key not found - Caused by changed Firefox profile or KeePass instance; changed OS user credentials; or KeePass config file may be corrupt
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Adding keefox-connection-message notification
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Notifying interested observers that the websocket has closed
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Pausing KeeFox.
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: panel showSearchResults started
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Removing all matched logins
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: setupButton_ready start
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Setting widget status
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: setupButton_ready end
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: setAllLogins start
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: setAllLogins end
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: setupButton_ready start
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Setting widget status
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: setupButton_ready end
Wed Dec 28 2016 10:30:58 GMT+0100:INFO: KeeFox paused.
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Websocket connection closed
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: resetAggregates finished
Wed Dec 28 2016 10:30:58 GMT+0100:DEBUG: Creating a metrics timer.
Wed Dec 28 2016 10:31:00 GMT+0100:INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Wed Dec 28 2016 10:31:00 GMT+0100:INFO: HTTP connection not refused. We will now attempt a web socket connection.
Wed Dec 28 2016 10:31:00 GMT+0100:DEBUG: Attempting to connect to RPC server webSocket.
Wed Dec 28 2016 10:31:00 GMT+0100:DEBUG: Trying to open a webSocket connection
Wed Dec 28 2016 10:31:00 GMT+0100:INFO: Websocket connection opened
Wed Dec 28 2016 10:31:00 GMT+0100:DEBUG: received message from web socket
Wed Dec 28 2016 10:31:00 GMT+0100:DEBUG: prepareFill accepted
Wed Dec 28 2016 10:31:00 GMT+0100:DEBUG: Looking for KeeFox Authorisation description text
Wed Dec 28 2016 10:31:00 GMT+0100:DEBUG: Starting KPRPCConnectionObserver
Wed Dec 28 2016 10:31:13 GMT+0100:DEBUG: metrics being sent

```

**Comment by m707** [comment]
Oh, sorry. Log continous as follows, when c&p the auth token from KP to FF:
``

Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: Starting KPRPCConnectionObserver
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: onStateChange keefox_tab: 196610
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: onLocationChange keefox_win: 0
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: panel showSearchResults started
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: Removing all matched logins
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: setupButton_ready start
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: Setting widget status
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: setupButton_ready end
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: onLocationChange keefox_tab: 0
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: Location changed. A tab is expecting a page load to occur very soon. 
Wed Dec 28 2016 10:46:52 GMT+0100:DEBUG: onStateChange keefox_tab: 196612
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: onStateChange keefox_tab: 720897
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: onDOMContentLoaded fired.
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: onStateChange keefox_tab: 196612
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: DOMContentLoadedHandler fired.
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: onDOMContentLoaded accepted a request.
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: Database is open: false
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: onDOMContentLoaded fired.
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: onStateChange keefox_tab: 131088
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: onStateChange keefox_tab: 131088
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: DOMContentLoadedHandler fired.
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: onDOMContentLoaded accepted a request.
Wed Dec 28 2016 10:46:53 GMT+0100:DEBUG: Database is open: false
Wed Dec 28 2016 10:47:01 GMT+0100:DEBUG: kfCommonDialogOnAccept started
Wed Dec 28 2016 10:47:01 GMT+0100:DEBUG: kfCommonDialogOnAccept finished
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: received message from web socket
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Removing keefox-connection-message notification
Wed Dec 28 2016 10:47:04 GMT+0100:INFO: KeePass install location found in preferences: C:\Program Files (x86)\KeePass Password Safe 2\
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Looking for the KeePass EXE.
Wed Dec 28 2016 10:47:04 GMT+0100:INFO: KeePass EXE found in correct location.
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: KeePassRPC install location inferred.
Wed Dec 28 2016 10:47:04 GMT+0100:INFO: Looking for the KeePassRPC plugin plgx
Wed Dec 28 2016 10:47:04 GMT+0100:INFO: KeePassRPC plgx found in specified or default location.
Wed Dec 28 2016 10:47:04 GMT+0100:INFO: Checking and updating KeePassRPC installation settings
Wed Dec 28 2016 10:47:04 GMT+0100:INFO: KeePass is not running or the connection might be established in a second...
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Observed an event: [xpconnect wrapped nsISupports],nsPref:changed,lastConnectedToKeePass
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Request to refresh KeeFox's view of the KeePass database received.
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Sending a JSON-RPC request
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: starting webcrypto encryption
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Refresh of KeeFox's view of the KeePass database initiated.
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Sending a JSON-RPC request
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: starting webcrypto encryption
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: received message from web socket
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: starting webcrypto decryption
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'data prep 1' took: 4
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: received message from web socket
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: starting webcrypto decryption
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'data prep 1' took: 0
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'key hash' took: 6
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'data prep 2' took: 0
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'generate HMAC' took: 2
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'import key' took: 1
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'key hash' took: 7
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'data prep 2' took: 1
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'generate HMAC' took: 0
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'import key' took: 1
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'aes-cbc' took: 3
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'utf-8 conversion' took: 1
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'aes-cbc' took: 2
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: decryption stage 'utf-8 conversion' took: 1
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Refreshing KeeFox's view of the KeePass database.
Wed Dec 28 2016 10:47:04 GMT+0100:INFO: At least one database is open.
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: panel showSearchResults started
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Removing all matched logins
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: setupButton_ready start
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Setting widget status
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: setupButton_ready end
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: setAllLogins start
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: setAllLogins end
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: setupButton_ready start
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Setting widget status
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: setupButton_ready end
Wed Dec 28 2016 10:47:04 GMT+0100:INFO: KeeFox feels very refreshed now.
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: FindMatchesRequestHandler accepted a request.
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Database is open: true
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: search for matches expects results from 1 frames.
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: findMatchesInManyFrames start
Wed Dec 28 2016 10:47:04 GMT+0100:INFO: Finding matches in a document. readyState: complete, autofillOnSuccess: false, autosubmitOnSuccess: false, notifyUserOnSuccess: false
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Adding configuration to cache
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: scanForOrphanedFields took: 0
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Database is open: true
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: findMatches processing 1 forms
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: about to get form fields
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: domtype: text
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: proccessing...
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: domtype: hidden
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: domtype: submit
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: domtype: hidden
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: domtype: hidden
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: usernameIndex: -1
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: actualUsernameIndex: 0
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: otherFields.length:1
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: no password field found in this form
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: searchCompleteTimeout: null. tabState.frameResponseCount: 1. tabState.frameCount:1
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Filling 1 sub frames
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: metrics being sent
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: fillAndSubmit started. automated: true, frameKey: undefined, formIndex: undefined, loginIndex: undefined
Wed Dec 28 2016 10:47:04 GMT+0100:DEBUG: Deleting any references to login data for recently completed async find logins call.

**Comment by gkaklas** [comment]
Are you sure that the security level is set to medium on both KeeFox and KeePass? (I'm not an expert, just brainstorming here).

**Comment by Dimas-sc** [comment]
Same here since KeePass 2.35

**Comment by m707** [comment]
@gkaklas, sry overseen your reply here :(. Yes I am 100% sure.

**Comment by nyvanga** [comment]
Same issue here. KeePass 2.35 + KeeFox 1.6.4 + KeePassRPC 1.6.4.0 + FF 52.0.2 (64bit)
Works perfectly on my laptop, with the same config. (Need to double check)

**Comment by m707** [comment]
After almost one year with trying this or that. I found *my* root of evil [here:](https://wiki.samba.org/index.php/Required_Settings_for_Samba_NT4_Domains#Windows_8.1_.2F_Windows_Server_2012_R2:_Error_code_0x80090345_launching_Windows_Credential_Manager)

Sry, forgot to mention that I am using a domain NT4 account against samba 4 (4.5.2/debain stretch at present) & sry for the noise. HTH
