### ISSUE TITLE
"Login to KeePass" button does not launch KeePass on Linux

### ISSUE THREAD

**Issue by iomintz** [kee-org/KeeFox#751]
Title is pretty self-explanatory.

## Steps to reproduce

0. Be on Ubuntu 16.04 LTS (all Linux distros?)
1. Launch KeePass.
2. Login.
3. Lock KeePass.
4. Press "Login to KeePass"

### Expected behavior

KeePass is opened and I'm asked for my master password (like on Windows).

### Observed behavior

Literally nothing. The KeeFox menu stays open.

**Comment by llankru** [comment]
Confirmed on Manjaro using following versions:

- KeeFox 1.6.4
- KeePassRPC 1.6.4.0
- KeePass 2.35
- Firefox 51.0.1
- Mono 4.6.1.3

**Comment by totorigolo** [comment]
Confirmed on Antergos (Arch) using following versions:
- FeeFox 1.6.4
- KeePassRPC 1.6.4.0
- KeePass 2.35
- Firefox 52.0
- Mono 4.8.0.495

For me, both "Launch KeePass" and "Login to KeePass" don't work.
