### ISSUE TITLE
KeeFox won't connect to KeePass

### ISSUE THREAD

**Issue by SteveGZr** [kee-org/KeeFox#758]
Since last Friday 2017-02-03 it's impossible for me and all of my colleagues to connect to KeePass. KeeFox shows the "Launch KeePass" Button and does not recognize, that KeePass is already running.
We all use Windows 7 with the newest Version of KeePass and KeeFox.

**Comment by dlech** [comment]
What troubleshooting steps have you taken so far?

https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting

If everyone in your office is experiencing the same problem, perhaps some security software was installed/updated that is blocking the TCP port.

**Comment by SteveGZr** [comment]
I talked to my colleagues again and some of them didn't experience the problem Friday. The problem occurred when they updated KeeFox. 
I have already checked TCP ports in the settings of KeeFox and KeePass and the settings in the security software.

**Comment by Darksider3** [comment]
Update to which version? I'm currently using KeeFox from the Firefox-Addon-Store(Whatever it's called correctly) with KeeFox 2.34, and it's just working fine(debian).

**Comment by SteveGZr** [comment]
KeeFox 1.6.4 and KeePass 2.35

**Comment by jmturner** [comment]
Same here. Firefox 52.0.2 (64 bit), KeePass 2.3.2, KeeFox 1.6.4 (running via Mono on Ubuntu).
Sample debugging output:

Sun Apr 09 2017 19:26:13 GMT-0400 (EDT):DEBUG: Websocket connection closed
Sun Apr 09 2017 19:26:13 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Sun Apr 09 2017 19:26:13 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Sun Apr 09 2017 19:26:13 GMT-0400 (EDT):DEBUG: Attempting to connect to RPC server webSocket.
Sun Apr 09 2017 19:26:13 GMT-0400 (EDT):DEBUG: Trying to open a webSocket connection
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: Websocket connection error
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: Websocket connection error end
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: Notifying interested observers that the websocket has closed
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: Pausing KeeFox.
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: panel showSearchResults started
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: Removing all matched logins
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: setupButton_ready start
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: Setting widget status
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: setupButton_ready end
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: setAllLogins start
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: setAllLogins end
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: setupButton_ready start
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: Setting widget status
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: setupButton_ready end
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):INFO: KeeFox paused.
Sun Apr 09 2017 19:26:24 GMT-0400 (EDT):DEBUG: Websocket connection closed
Sun Apr 09 2017 19:26:25 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Sun Apr 09 2017 19:26:25 GMT-0400 (EDT):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Sun Apr 09 2017 19:26:25 GMT-0400 (EDT):DEBUG: Attempting to connect to RPC server webSocket.
Sun Apr 09 2017 19:26:25 GMT-0400 (EDT):DEBUG: Trying to open a webSocket connection

**Comment by ACinnamonUserInUK** [comment]
I got this fixed but, unfortunately, I can't remember how. Possibly it was by correctly filling in the KeeFox field that asks for the location of the KeePass executable. Good luck!

**Comment by m1ckrz** [comment]
I have all settings correct. Even removed/reinstalled KeeFox and still not working. Only options is to "Launch Keepass" (already running). Tried clearing plugin cache also and disabled all triggers. No joy...

**Comment by Bobriks** [comment]
Works fine with v.keepass 2.20.
After update to 2.35 lost connection.
From folder "plugins" (v.2.20) i copy file KeePassRPC.plgx to folder "plugins" v.2.35
After that, keefox ask autorization and work fine 2.35.
P.S. bad english )
