### ISSUE TITLE
Keefox icon frozen in grey and not able to click on it

### ISSUE THREAD

**Issue by Asimov500** [kee-org/KeeFox#759]
I have an issue sometimes when the keefox icon gets frozen. So that clicking on it has no effect.
If I open another window it works. Now even when it is frozen it still auto fills in forms.

I am using mozilla firefox 51.0.1(32 bit)

I don't know how to find the keefox version but it says last up dated 19 January 2017

**Comment by Asimov500** [comment]
I am still having the problem that keefox is frozen. So here is some more information. I am running on windows 10 with the same mozilla as I mentioned above. On my other computer at home I am not having the same problem. It is like there is a grey box around it, and clicking on it does nothing.
![keefox](https://cloud.githubusercontent.com/assets/19980164/23850965/9554d2a6-07d9-11e7-904d-cc325982cb42.png)

**Comment by ToXinE** [comment]
same here. My firefox stay open the whole week.

**Comment by ToXinE** [comment]
any updates ? 
I have several keepass databases opened and some are locked

**Comment by Asimov500** [comment]
I have been hoping for a solution to this problem too. However if you close your browswer and open it, or even open a new browser window you should be able to access your information. Failing that you can go into keepass itself.
