### ISSUE TITLE
Firefox 52.0 (32bit) and Keepass 2.3.5 with Keefox 1.6.4 - FAILURE

### ISSUE THREAD

**Issue by roswitina** [kee-org/KeeFox#765]
With Firefox 52.0 (32bit) and Keepass 2.3.5 with Keefox 1.6.4 - FAILURE I cant login to database. With Keepass 2.3.4 all is OK.

Rosi

**Comment by SteveGZr** [comment]
What do you mean with "cant login to database"? Are you able to connect your KeeFox with your KeePass?
