### ISSUE TITLE
Make KeeFox work alongside Firefox's default password manager?

### ISSUE THREAD

**Issue by n-o-o-b** [kee-org/KeeFox#773]
Hi, new user here. I have the username and password for my router saved using Firefox's built in passsword manager (I use it to access the router settings). Ever since I installed KeeFox, the dialog that appears when I click on the link to the router settings page I have bookmarked is cut off at the bottom, and it looks really weird. I would rather keep things as they are and not add these details to KeePass. Is there any way you guys could make KeeFox work happily alongside Firefox's password manager?

This is what the dialog looks like when I click on the link when I first launch my browser (and KeePass is not running):
![keefox](https://cloud.githubusercontent.com/assets/19697175/26596085/7956d080-4565-11e7-8682-2de885a5218d.png)

This is what the dialog looks like when I click on the link after I have launched KeePass:
![keefox 2](https://cloud.githubusercontent.com/assets/19697175/26596132/9626b432-4565-11e7-98cb-e13b3b88e139.png)

**Comment by levicki** [comment]
Why not just remove your router credentials from Firefox and save them in KeePass database? The whole point of using KeePass and KeeFox is to keep your passwords safe, no? Why would you want to keep using Firefox password manager?

**Comment by n-o-o-b** [comment]
Whether or not I decide to save the credentials in KeePass, the fact remains that KeeFox messes up the dialog box. I might well decide to put the info into KeePass and use it with KeeFox instead of with Firefox's password manager, but surely KeeFox shouldn't be cutting off the bottom of the window like that?

In fact, I just tried adding it, and the dialog box is still cut off even with KeeFox:
![keefox 3](https://user-images.githubusercontent.com/19697175/27537149-66c961e8-5a6a-11e7-8792-0e4c2e5a185e.png)

**Comment by levicki** [comment]
Fair enough, it should not cut off. Do you perhaps have multiple credentials for the same URL? It shouldn't create a dropdown menu which actually pushes buttons down otherwise.
