### ISSUE TITLE
Broken labels

### ISSUE THREAD

**Issue by agilob** [kee-org/KeeFox#777]
![screenshot_20170423_095745](https://cloud.githubusercontent.com/assets/2544251/25312224/b90a65a6-280b-11e7-95dd-87374a53487f.png)
THat's what keefox looks for me on Firefox 53, archlinux.

**Comment by luckyrat** [comment]
That means KeeFox was unable to initialise correctly. Probably there is an incompatible add-on or a bug with Firefox specific to your archlinux build so try a process of elimination and then if nothing helps, try looking at the KeeFox log file and the browser console for error messages to help diagnose the problem.
