### ISSUE TITLE
Auto-Lock Database on Exit

### ISSUE THREAD

**Issue by luckyrat** [kee-org/KeeFox#78]
I'd like a feature to be added where the keepass database is locked when Firefox closes.  That way if someone else uses my computer, they have to provide the master password whenever they start up firefox (not just when keepass is first started).  Currently if I were to close Firefox after using keefox, the database is still open who whomever wants to view it.

**Comment by mygithuber** [comment]
Any news about this request? Locking database on Firefox exit would IMHO improve KeePass security...
Thx!
