### ISSUE TITLE
KeeFox gets signed out of KeePass during database synchronization.

### ISSUE THREAD

**Issue by darzur** [kee-org/KeeFox#782]
Hi,
It happened just today after computer restart due to W10 update. Now every time KeePass synchronizes local database with Dropbox account KeeFox gets logged out. I'm working on local database, but after every change it's synchronized with Dropbox. When I disable this synchronization everything seems to be working as usual.

**Comment by darzur** [comment]
Just checked and it happens not only when synchronizing with Dropbox, but during synchronization in general.

**Comment by darzur** [comment]
Still not resolved after update to 1.7.0. I'm wondering if I'm only one with this problem...

**Comment by vanowm** [comment]
My KeeFox keeps saying I need to login, even when KeePass is already logged in.
Windows 10 x64, Firefox 55.0.2/Waterfox 55, KeePass 2.36, KeeFox 1.7.0/1.7.2b1
Debug logging doesn't show anything abnormal.

**Comment by darzur** [comment]
Hi,

What do you mean by removing all leftover settings of KeeFox? I've uninstalled it and then installed again but it remembers all my setting so I guess I should delete something more...

**Comment by darzur** [comment]
Hi,

What do you mean by removing all leftover settings of KeeFox? I've uninstalled it and then installed again but it remembers all my setting so I guess I should delete something more...

**Comment by vanowm** [comment]
After uninstall of KeeFox, go to `about:config` and type in the filter field: `keefox` 
It should show you bunch of settings, right click on each one of them that has @ in it's name and select "Reset" (make sure you don't touch settings without the @ character!)

**Comment by darzur** [comment]
Did that but it didn't helped in my case.  Every time KeePass syncs it's database KeeFox gets logged out.

**Comment by vanowm** [comment]
But did you disable auto sync in KeePass? (also which sync plugin do you use?)

**Comment by darzur** [comment]
Well,
If I disable syncing then there is no point of this issue. It happens only during syncing. BTW. I have auto syncing disabled, but occasionally have to sync manually and then it logs out. I don't use any sync plugin - my DB is synced with local OneDrive folder

**Comment by vanowm** [comment]
I just tested it on a fresh Windows, fresh Firefox and fresh KeePass/KeeFox with new database. Everything works fine.
This suggests that it's probably something on KeePass end or in database settings even.

**Comment by darzur** [comment]
Might be something with database as same thing happens on another (portable) instances of FF an KeePass. Will try to create new database for testing

**Comment by darzur** [comment]
And it's it. Created new database and everything works as it should. Is there any way to debug what might be a problem? I cant just delete this database and start over from scratch..

**Comment by vanowm** [comment]
You could try export it and then import.

**Comment by darzur** [comment]
Did that and everything is working again. :) Thanks for this tip. Its unbelievable that I was fighting with that for almost half year and solution was so close...

**Comment by JoeSz** [comment]
Same here! Thanks for the heads up 👍
