### ISSUE TITLE
Can't log in the new accounts.google.com page

### ISSUE THREAD

**Issue by favorart** [kee-org/KeeFox#783]
![log-in-google](https://cloud.githubusercontent.com/assets/9784285/26029870/d566f3ca-3848-11e7-8d4c-94c09a1c4e5a.png)
The similar issue with pages of separated log (in like login.skype.com).

**Comment by bmintz** [comment]
KeeFox does have a multi page password functionality. Within KeePass' View Entry dialog, head to the KeeFox tab and try adding page 2 to the password field.

**Comment by JBPlinn** [comment]
I confirm this DOES NOT work (page 2 in Keepfox tab). I have multiple gmail accounts and keefox is completely lost by this new login page. Even if I select then entry to log with Keefox choses the 1st one....

**Comment by favorart** [comment]
Yes, there is 2-page-support in keefox, but...

I have tried recreate keepass-records for microsoft and google accounts for their new log-in-pages.
Keefox creates the keepass-records successfully, but I could not use them to log-in. 
First, when I open the web-page, I must "discover forms", then login or password can be inserted. 
As you can see in screenshot, the login has been pasted incorrect way, so I could not continue!
![default](https://cloud.githubusercontent.com/assets/9784285/26407710/86eea788-40a4-11e7-99cc-6baf6592bca8.png)

Could you, please, check out the log-in process for firefox.
Thank you.

**Comment by brainfence** [comment]
Following KeePass JSON works for me (even with 2FA):

> {
   "version":1,
   "formFieldList":[
      {
         "name":"password",
         "displayName":"KeePass password",
         "value":"{PASSWORD}",
         "type":"FFTpassword",
         "id":"",
         "page":1
      },
      {
         "name":"identifier",
         "displayName":"KeePass username",
         "value":"{USERNAME}",
         "type":"FFTusername",
         "id":"hiddenEmail",
         "page":1
      },
      {
         "name":"ca",
         "displayName":"ca",
         "value":"",
         "type":"FFTusername",
         "id":"ca",
         "page":1
      },
      {
         "name":"totpPin",
         "displayName":"totpPin",
         "value":"{TOTP}",
         "type":"FFTusername",
         "id":"totpPin",
         "page":2
      }
   ],
   "alwaysAutoFill":false,
   "neverAutoFill":false,
   "alwaysAutoSubmit":false,
   "neverAutoSubmit":false,
   "priority":0,
   "altURLs":[
      "https://accounts.google.com/signin/v2/challenge/totp"
   ],
   "hide":false,
   "blockedURLs":[],
   "regExBlockedURLs":[],
   "regExURLs":[],
   "blockHostnameOnlyMatch":false,
   "blockDomainOnlyMatch":false
}
>
{TOTP} is provided by [KeeOtp](http://keepass.info/plugins.html#keeotp).

**Comment by xbcd** [comment]
I also have issues with my several Google accounts, 
set up with different "Priority override" numbers in their KeeFox > General tab entries in KeePass database.

My **main** account ("Priority override" = 0) is working 100%, 
as long as I don't click the list of matched logins.

If I have removed the Google account from my Firefox browser, 
_(to make Firefox "forget" that Google account, that is)_,
KeeFox will auto-fill my email address, and when I click the Next button, 
it will auto-fill my password, and when I click the Next button again, 
I am logged into that main account.

And if I have **not** removed that Google account from my Firefox browser,
it will just auto-fill my password, and when I click the Next button again, 
I am logged into that main account.

However, if I try to use the standard KeeFox procedure, 
clicking an entry in the list of matched logins,
it will not work at all. 
Neither the main "Priority override" = 0 account, nor any of the others.

So for now, my workaround is to right-click the entry in the list of matched logins,
then select "Copy username", paste it in and click the Next button,,
then select "Copy password", paste it in and click the Next button.

**Comment by bmintz** [comment]
@xbcd I don't think that's the same issue (let me know if it is!)
Please open a new issue.

**Comment by bdurrer** [comment]
I am pretty sure that the root of this issue was reported in #638 
The solution is already published too, it's part of the latest KeeFox:

- Go to the KeeFox Settings
- Open the second tab
- Activate the last checkbox (Trigger Change/Input Event after auto-fill)

If that does not solve the problem for you, the workaround is simple: focus the field, enter a space and delete the space again. This updates the website's internal data model with the correct value.

**Comment by favorart** [comment]
> Activate the last checkbox (Trigger Change/Input Event after auto-fill) ...

Thank you, **bdurrer**, I turned on this checkbox and coping of login data is performing well.

Now I understand, that my problem also touches upon auto-sending the password.
The incorrect button `Forgot email?` is pushed, when I choose the login in the keeFox list
(instead of the `next` button).
And that's why after some redirections keeFox could not find the password-form.

> Following KeeFox JSON ...

does not define the correct button.
Thank you,  **brainfence**, anyway.

Working solution is to disable the `auto-send` in keeFox options.
It is interesting to find out how to fix this page.
I didn't find the manual of filling `Form fields` in keeFox tab of password entity of keePass. 
I suppose the problem is there.
