### ISSUE TITLE
Associate domains

### ISSUE THREAD

**Issue by D219** [kee-org/KeeFox#784]
Some website share the same logins. A simple example is stackoverflow.com and stackexchange.

Is there a way to signify to KeeFox that two website are the same instead of saving the login again and again, and have trouble when you change them?

LastPass have a option for that, which is preconfigured.

**Comment by r2evans** [comment]
In the specific entry modal, go to *KeeFox* (tab) > *URLs* (sub-tab) and enter the alternate domains. Is that what you're looking for?
