### ISSUE TITLE
Thunderbird 52/Caldav AutoLogin stopped working

### ISSUE THREAD

**Issue by Markus87** [kee-org/KeeFox#785]
Starting with Thunderbird 52 the auto fill of the caldav login dialogs stopped working.
I debugged the issue and think that the dialog did change from the previous version: EnterUserPasswordForCrossOrigin2=%1$S is requesting your username and password. WARNING: Your password will not be sent to the website you are currently visiting!

I suppose KeeFox does not auto fill "dangerous" login forms on purpose and this must be a bug in Thunderbird, somehow mistaking the caldav login as cross origin.

I am going to investigate why Thunderbird thinks its cross site and file a bug on their bug tracker if it seems like an error.

What do you think?

Also thanks for this great extension!

**Comment by dlech** [comment]
It looks like we are not checking that string at all.

https://github.com/kee-org/KeeFox/blob/e990e24590a4ae9ecd702402b1fe10c4f544c506/Firefox%20addon/KeeFox/chrome/content/commonDialog.js#L504

It should be easy enough to add it.

**Comment by Markus87** [comment]
Yeah, as a workaround I did that for me:
```diff
*** commonDialog_org.js 2017-05-20 19:25:47.900393173 +0200
--- commonDialog.js     2017-05-20 19:25:34.901045358 +0200
***************
*** 430,435 ****
--- 430,456 ----
                      }
                  }
              }
+                 
+            if (host.length < 1)
+             {
+                 // e.g. en-US:
+                 // %1$S is requesting your username and password. WARNING: Your password will not be sent to the website you are currently visiting!
+                 var currentRealmL10nPattern = "";            
+                 try 
+                 {
+                     currentRealmL10nPattern = this._cdBundle.GetStringFromName("EnterUserPasswordForCrossOrigin2");
+                 } catch (exception)
+                 {
+                 }
+ 
+ 
+                 currentRealmL10nPattern = currentRealmL10nPattern.replace("%1$S","(.+)");
+                 let regEx = new RegExp(currentRealmL10nPattern);
+ 
+                 let matches = document.getElementById("info.body").firstChild.nodeValue.match(regEx);
+                 if (matches !== null && typeof matches[1] !== "undefined" )
+                     host = matches[1];
+             }
  
              if (host.length < 1)
              {

```

But I think in the context of the warning it would not be ok to fill it automatically anyways?

I posted a bug for Thunderbird(https://bugzilla.mozilla.org/show_bug.cgi?id=1366463), this warning should not come at all for every caldav calendar. 
If the bug gets fixed in Thunderbird I suppose there is no need for changes in KeeFox at all.

**Comment by dlech** [comment]
Due to the recent split between Thunderbird and Firefox extensions, we have started a fork of KeeFox specifically for Thunderbird. We are calling this new extension KeeBird and the code and issue tracking are now in a new GitHub repository. If anyone is still interested in getting this issue resolved, please let us know by opening a new issue at https://github.com/kee-org/keebird/issues and copy/paste any relevant information (or at least link to this issue).
