### ISSUE TITLE
Temporarily Disable Keefox ("Pause" button)

### ISSUE THREAD

**Issue by boolbag** [kee-org/KeeFox#786]
For some websites, I have multiple logins (e.g. me & girlfriend).
Sometimes Keefox picks the wrong user, and even when manually picking the right user from the list, Keefox re-fills the fields with the wrong user. For these troubling buggy cases, I am having to manually disable the add-on, which involves a Firefox re-start.

Is there instead a "Pause Keefox" functionality that I haven't found somehow, or could this please be added?

**Comment by bdurrer** [comment]
The answer is yesno 😄 

There is no pause functionality, but there are better options than disabling KeeFox:
- make an entry invisible to KeeFox on the "KeeFox" tab of an entry, inside KeePass
- on the same tab: change the priority order. Lowest number has highest priority.
- on the same tab: disable autofill
- switch the URL Matching to "exact" on the "URL" sub-tab. This prevents KeeFox from trying to fill out the login/pw on other forms (e.g. profile forms) and thus is less annoying
- you realize that your KeePass DB fails the "separation of concerns" principle: Your GF's data belongs in an separate DB! 😉

**Comment by boolbag** [comment]
Thank you for your tips @bdurrer !
I hadn't found the "priority" box... That really helps!
Yes, you're right about separation of concerns. I don't have all her passwords, it's just for a couple of websites where we periodically have to log in to each other's account.
