### ISSUE TITLE
Cannot sign on to Capital One

### ISSUE THREAD

**Issue by pmorgan111** [kee-org/KeeFox#788]
I am having trouble signing on to Capital One at https://servicing.capitalone.com/c1/Login.aspx with KeeFox using the Firefox browser.

Native KeePass has no problem performing Auto-Type of username/password and then submitting the page.

KeeFox auto-fills but issues an error on the username: "Please enter required information"

Is there a bug in KeeFox or I am doing something wrong? Perhaps there is a setting in KeePass or KeeFox that would help for this site?

Thanks for any help.

**Comment by kmantel** [comment]
I was having this problem for a long time on multiple sites. It seems to have been fixed by [release 1.7.0](https://github.com/kee-org/KeeFox/releases/tag/v1.7.0) by selecting the following option
![untitled](https://cloud.githubusercontent.com/assets/1592123/26771539/f8c1f522-498c-11e7-90d0-0b852a718bac.png)

**Comment by pmorgan111** [comment]
Thanks for the information. I'll have to wait for the extension to be verified as the current version of Firefox does not allow KeeFox 1.7.0 to be installed and I do not have the time to "play" with other versions of Firefox that would allow it. Because of this problem I had decided not to use KeeFox. I look forward to using release 1.7.0 as I definitely understand the value of using this extension. Thanks again for your help.

**Comment by kmantel** [comment]
In case you found that "feature" annoying like I did, you can bypass it like this https://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/

**Comment by pmorgan111** [comment]
Good information, thanks for sending it. I figured there was a way to override Firefox's signing feature. At this point though I don't have time to play with it. I've been using KeePass without KeeFox for several months, so I can wait a bit longer until I am able to install this extension conventionally. 

 

 

 

-----Original Message-----

**Comment by TeutonJon78** [comment]
I can verify that the new experimental trigger setting works as well. There were a lot of websites that this was starting to become a problem for.

**Comment by bdurrer** [comment]
I can confirm that #638 already solved this.
