### ISSUE TITLE
KeePassRPC 1.7 plugin needs a newer version of KeePass

### ISSUE THREAD

**Issue by gavinmporter** [kee-org/KeeFox#790]
Restarted Firefox with the updated KeeFox 1.7 plugin. Installed the new KeePassRPC.plgx file and restarted KeePass2.

Error message states that 'The plugin cannot be loaded. A newer KeePass version is required to open this file.'

I'm running KeePass 2.25 on Ubuntu Trusty (14.04). All works fine with Keefox 1.6.4.

Have also tested with KeePass 2.32 on Ubuntu Xenial (16.04). Same error.

Has the minimum required version of KeePass changed from 2.19? (https://github.com/kee-org/KeeFox/wiki/en-|-Installation-|-Linux)

Thanks,
Gavin

**Comment by auburus** [comment]
Same problem here, I've noticed it today.

**Comment by aabeling** [comment]
With https://github.com/kee-org/keepassrpc/commit/3d46d7d362bfc37946be4e61dc6c94bb55aa7fa4 the minimum version changed to 2.34, right?
So we ubuntu 16.04 users have to upgrade?

**Comment by gavinmporter** [comment]
Thanks for spotting the change. I can confirm that 2.35 from the PPA works on Ubuntu 14.04 and 16.04.

Updated wiki instructions for Linux.
