### ISSUE TITLE
keefox 1.70 broken with keepass2 2.28  

### ISSUE THREAD

**Issue by permutation-jim** [kee-org/KeeFox#791]
The repo version of keepass2 for debian wheezy is 2.19 while jessie is 2.28.  Keefox docs say it requires keepass2 version 2.34 of higher, and debian won't get that till stretch goes live in late June. KeeFox version 1.7 is broken for me after the last update and I can't seem to get older versions to work, either.

I've checked the mono installation and everything worked till I rebooted with the new KeeFox version.  
Is there something I'm missing?

**Comment by saierd** [comment]
The same problem exists on Ubuntu 16.04, which only has [KeePass 2.32](https://packages.ubuntu.com/de/xenial/keepass2) at the moment.

**Comment by permutation-jim** [comment]
Workaround is to remove keefox, remove current keepass2 (from repo), download the latest portable version (2.36, in my case), unzip the files into the old folder (/usr/lib/keepass2), then install keefox (1.70) again. Configure Keefox to look in rhe right folder, then it will launch it for you.

Worked for me!

-Jim
