### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mvbentes** [kee-org/KeeFox#793]
As came up on an [old discussion](https://zohodiscussions.com/keefox/topic/keefox-to-keepass-connection-request), it would be nice to have an option to **not ask to connect after the request is cancelled** or even to **not ask at all until a manual request is started by the user**, even if in about:config.

Rationale:
I have chosen the high security setting. On my work computer, I am constantly closing firefox due to limited RAM, so I get asked to type the connection string some 20+ times a day. Most times, though, I do not even need to login anywhere, so I could refrain from connecting to KeePass if only KeeFox would let me do so.

I really like the extension, but I feel the medium security setting, storing the connection password in firefox's password manager, is not enough. The high setting, on the other hand, is being more of a hassle than it needed be.

**Comment by BoffinbraiN** [comment]
You should only have to enter the KeeFox-KeePass authentication code once per year or after major updates, not every time you load Firefox.
