### ISSUE TITLE
KeepassRPC outdated for Keepass 2.36

### ISSUE THREAD

**Issue by pentix** [kee-org/KeeFox#794]
## System Setup
- Windows 7
- Firefox 54.0
- KeePass 2.32,  configuration as installed with Keefox (Updates activated!)

## What happens when I start Keefox in Firefox
![keepass_old](https://user-images.githubusercontent.com/3193006/27398284-88cd9df4-56b9-11e7-8833-ce4311444312.PNG)

## What I've tried
- Reinstall KeeFox
   - Installation dialog did not pop up afterwards
- Get portable version of current Keepass v2.36, copied old KeepassRPC into `plugins/`. Adjusted the path  in the KeePass settings. Did not work.
- Copy the current KeepassRPC plugin from Firefox' profile directory (as stated here: https://github.com/kee-org/KeeFox/wiki/en-%7C-Installation-%7C-Linux#install-keepassrpc-manually) The following happens:

![keepass_236](https://user-images.githubusercontent.com/3193006/27398226-5f2f7a4e-56b9-11e7-905f-94b541ed2025.PNG)

So it seems KeeFox needs to provide an update?
It also would be nice if there was an option to download the `KeePassRPC.plgx` directly from Keefox' website.

**Comment by dlech** [comment]
What version of KeeFox are you using?

Are you using KeePass 2.32 or 2.36? You mention both.

If you run `KeePass.exe` from the command line with the `--debug` option, does it give a better message?

**Comment by pentix** [comment]
I am using the latest version of KeeFox, which seems to be 1.7.0, at the moment.

> Are you using KeePass 2.32 or 2.36? You mention both.
I mentioned both because I tried both 😉 Previously installed was 2.32 but 2.36 doesn't work either.

I'll try this as soon as possible, thanks for your feedback.

**Comment by notnarb** [comment]
I'm running 2.32 (the latest version available with Ubuntu 16.04) and I am experiencing the same issue (though it looks like as of: https://github.com/kee-org/keepassrpc/commit/3d46d7d362bfc37946be4e61dc6c94bb55aa7fa4 the minimum version has been changed to 2.34?)

> If you run KeePass.exe from the command line with the --debug option, does it give a better message?

no (at least not for me):
![selection_201](https://user-images.githubusercontent.com/1731591/27410234-1d4c197a-569b-11e7-9edd-28477802eccd.png)
(I don't know how to check the KeePassRPC version so I ran strings on it to get the build? date)  My two previously made backups of KeePassRPC worked fine (.backup.2017-06-xx where xx is the day that keefox instructed me to upgrade from that version)

Current KeeFox version:
![selection_202](https://user-images.githubusercontent.com/1731591/27410237-1f9198f4-569b-11e7-8e6b-606054245748.png)

**Comment by pentix** [comment]
@dlech I did the same as @notnarb tried. A message said that the Compilation of the plugin failed and that the log had been saved. 

Please have a look at this:
[keepass_v2.36_error_log.txt](https://github.com/kee-org/KeeFox/files/1095772/keepass_v2.36_error_log.txt)

**Comment by dlech** [comment]
Do you have any other plugins installed? It looks like there are conflicting versions of Jayrock.Json. 

You can also try clearing the plugin cache.

**Comment by pentix** [comment]
No, I don't have any other plugins installed. Also for example the Keepass v2.36 (portable) installation is absolutely new, so there shouldn't be anything in the cache... Nevertheless I'll try to clear the cache, thanks!

Why should there be multiple versions of Jayrock.Json? 😮  Is there something I can do about this?

**Comment by dlech** [comment]
On second look, it seems that it is not Jayrock.Json, but System.Core that is the problem. It could be that KeePass is running with the .NET 3.5 framework instead of 4 or newer. 

You could try editing KeePass.exe.config. [example](https://sourceforge.net/p/keepass/discussion/329220/thread/c00b8889/)

**Comment by notnarb** [comment]
upgrading to 2.36 fixed my problem on Mono 4.2.1 so it looks like my problem was different after all

**Comment by pentix** [comment]
Thanks! Do you think installing the current .NET 4.5 will fix this?  I will try uncomment the `supported-runtime` var in the config. Maybe this helps. I'm going to report this back to you. Thanks again!

**Comment by krbvroc1** [comment]
As a data point, I am running 2.36 on Centos 7 which uses mono 4.2.4 without issue.

**Comment by pentix** [comment]
@dlech I tried to install .NET 4.6.1. The installer mentioned that it was already installed - Yes, it was indeed. So I also tried to adjust the configuration as stated in your link. The `<supported runtime>`-tag was already included. (uncommented)

Sadly, this didn't change anything... What could I do now? Try to remove everything and install it completly again? It appears strange to me that KeeFox doesn't display it's *Keefox installed - Download Keepass here*-setup-page after I reinstalled it. Maybe I should remove the old KeePass first?

**Comment by pentix** [comment]
So I tried to reinstall *everything*: 
- Uninstalled KeePass
- Removed the portable version
- Removed KeeFox from Firefox
- Deleted `extensions/` and `KeeFox/` in `%appdata%/Roaming/Mozilla/Firefox/profiles/xxxxxx/`
- Searched the windows registry for `keepass` and deleted those entries

When I reinstalled Keefox, the setup page didn't show up. So I invoked it manually. The page stated that KeePass would already be found & installed. When I click on *Install* I'm there's an error *Could not install KeePassRPC[...] This is usually happens when you try to install KeePass somewhere you're not allowed to create files*

The same happens when I open up the plugin upgrade page.


Any ideas on how to really reinstall the KeeFox plugin without losing the entire profile?

**Comment by pentix** [comment]
I repeated the same steps as I mentioned above. But instead of trying to install KeePass using KeeFox
I downloaded the regular setup version and installed it. Then the error on installing KeeFox disappeared and everthing works now.

Thanks for your help!

**Comment by lpalgarvio** [comment]
See #806 for linux
