### ISSUE TITLE
Keefox breaks tab restore since 2017-07-27 (56.0.1a)

### ISSUE THREAD

**Issue by nailyk-fr** [kee-org/KeeFox#799]
**Steps to reproduce:**

1. Setup firefox to open tabs on next launch, setup an home page
2. Install keefox addon, 
3. Pin some tabs, let some other opened, 
4. Close nightly, 
5. Launch nightly. 

Tested on nightly 2017-07-26 (version before the 'restart to update nightly' was fine) but testing this with mozregress is not really relevant. 
IIRC last known good version was 2017-07-24.
Original issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1384697
(tested with old and new FF profile)

**Actual results:**

All tabs are blanks, except the 'active one while closing' who now display the default page. 

**Expected results:**

Tabs are restored.

**Comment by mirh** [comment]
I'm on 56b6 and I have no problem. 
Test pilot seems to give me nuisances on the other hand.

**Comment by nailyk-fr** [comment]
56b6 should still be running the old plugin API. 
Thanks for pointing, the dev is already working on the new API, no need to left this open.

**Comment by luckyrat** [comment]
session restore in recent Firefox versions seems to be a bit of a mess. I've seen problems with and without KeeFox installed but only intermittently. https://bugzilla.mozilla.org/show_bug.cgi?id=1388628 is one example bug but there's a pretty complex tangle of related issues that I've not had time to really dive into - just have to trust the Mozilla team will fix it soon and hold off on Firefox auto-updates in the mean time.
