### ISSUE TITLE
Can't login to Google accounts

### ISSUE THREAD

**Issue by qeerl** [kee-org/KeeFox#800]
Hello,

When I try to login i'm redirected here:

https://accounts.google.com/signin/usernamerecovery?continue=https%3A%2F%2Fwww.google.fr%2F&hl=fr

Auto-fill does not do anything, I have to select manually the account.
I've tried to to delete the Keepass entry and have Keefox recreating it, the result is the same.    

Any solution please? Thanks !

**Comment by BoffinbraiN** [comment]
The new Google login page is a pain in the backside. The email address fills in fine on the initial screen, but I have to keep opening the KeeFox menu and right-clicking my Google account to copy the password to paste in the next step.
