### ISSUE TITLE
Nightly 57.0 breaks KeeFox

### ISSUE THREAD

**Issue by Larusek** [kee-org/KeeFox#801]
As of Nightly 57.0 version KeeFox is unusable. Any ETA to make it compatible again?

**Comment by stayen** [comment]
Correct; please read the below:
https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

Starting from Firefox version 57 (will be published in  November), so called legacy extensions will be unconditionally disabled, that includes current version of KeeFox.

**Comment by luckyrat** [comment]
Please see http://keefox.org/news/detail/2017/09/19/introducing-kee-20
