### ISSUE TITLE
KeeFox no longer filling fields on in FF56

### ISSUE THREAD

**Issue by hackel** [kee-org/KeeFox#803]
Since upgrading to Firefox 56 (currently at beta 2), KeeFox hasn't been able to match any domains for auto-fill.  It's still working, and I can search my KeePass DB from the extension.  I just can't get it to match any domain for some reason.  I can still search and manually use the copy/paste functions of the addon to log into sites, at least.  Not sure how important this is with FF57 looming, but I thought I would mention it.

**Comment by luckyrat** [comment]
I've not noticed any problems with the dev edition but I'm not able to test 56 beta at the moment because of a critical bug that leads to session corruption. Mozilla reckon they'll have it fixed in a few days though so I will most likely be able to investigate at the weekend.
