### ISSUE TITLE
Keefox doesn't detect keepass anymore without explanation

### ISSUE THREAD

**Issue by stemy2** [kee-org/KeeFox#804]
Hello,

Since today, keefox stopped working without reason nor explanation. I haven't changed anything to keepass or keefox, but this is like i hadn't installed keepass or Mono. Both are installed and the pglx file is listed in the plugins, so i have no clue of the reason of this malfunctioning.

**Comment by Mech0z** [comment]
Are you using Firefox nightly? If so https://twitter.com/FirefoxNightly/status/897129771632652289 (I know its Lastpass, but same APIs that have been restricted now)

**Comment by stemy2** [comment]
No, this is the stable version. And the problem solved itself.
