### ISSUE TITLE
KeeFox, KeePassRPC and Mono 4.x / 5.x

### ISSUE THREAD

**Issue by queaker** [kee-org/KeeFox#806]
Hi

I have a problem using KeeFox 1.7.2b with KeePass using Mono on Mac OS X. After the Last Update KeePassRPC.glx was updated and isn't working with KeePass using Mono 4.2.3 or Mono 5.2.0. 

The error message is: "The plugin cannot be loaded. A newer .NET Framework is required."

<img width="346" alt="keefox" src="https://user-images.githubusercontent.com/4228208/29556949-d374c564-8727-11e7-8d4e-a479a76fa9b8.png">

Actually - i have no clue how to solve this problem....

**Comment by luckyrat** [comment]
Which version of KeePassRPC.plgx are you loading?

Where did you download it from?

Does the hash of the file match any of the following?
MD5: 9925ce9739855d5fcb0941fa9da953fa
SHA256: 5196d04d1e395fa51ec535ef213f22128156811f8fce079c89974d0845ff60a8

**Comment by lpalgarvio** [comment]
Same problem here.

Linux Mint 18 Sarah
Firefox 55.0.2 (64-bit)
KeePass 2.36
KeePassRPC 1.7.1 from https://github.com/kee-org/keepassrpc/releases/download/v1.7.1/KeePassRPC.plgx
KeeFox 1.7.2b1

**Comment by lpalgarvio** [comment]
Installed KeeFox 1.7.0 stable (older version) and is now working again.

**Comment by luckyrat** [comment]
You need keepassrpc 1.7.2 rather than 1.7.1

Maybe there is an outdated link to 1.7.1 somewhere?

**Comment by queaker** [comment]
KeepassRPC 1.7.1, which is downloadble, isn't working either. Same error message, referring to the newer .NET Framework. And Keepass 1.7.0 isn't installable vom addons.mozilla.org running Firefox 54.0.1 (64-Bit) on Mac OS X.

![grafik](https://user-images.githubusercontent.com/4228208/29668802-bae07f46-88e1-11e7-9282-9096e5bcbf66.png)

What am i doing wrong?

**Comment by luckyrat** [comment]
You can download 1.7.2 from here: https://github.com/kee-org/keepassrpc/releases/download/v1.7.2/KeePassRPC.plgx

There was an old link to 1.7.1 on http://keefox.org/upgrade which is probably what has caused the confusion. Sorry about that.
