### ISSUE TITLE
Keefox Error

### ISSUE THREAD

**Issue by wardog83** [kee-org/KeeFox#812]
---------------------------

---------------------------
ERROR! Please click on this box, press CTRL-C on your keyboard and paste into a new post on the KeeFox forum (http://keefox.org/help/forum). Doing this will help other people to use KeeFox without any unexpected error messages like this. Please briefly describe what you were doing when the problem occurred, which version of KeeFox, KeePass and Firefox you use and what other security software you run on your machine. Thanks! Technical detail follows: System.NullReferenceException: Object reference not set to an instance of an object.

   at KeePassRPC.KeePassRPCClientConnection.Encrypt(String plaintext)

   at KeePassRPC.KeePassRPCClientConnection.Signal(Signal signal, String methodName)
---------------------------
OK   
---------------------------
Keepass 2.36
Keefox 1.7.2
Firefox 55.0.3 (64)

**Comment by freaksterrao** [comment]
This seems to be what was fixed as part of KeePassRPC plugin 1.7.3 (https://github.com/kee-org/keepassrpc/releases/tag/v1.7.3.1)

**Comment by wardog83** [comment]
I confirm. Fixed.
