### ISSUE TITLE
Firefox 57.0b3 and soon final  57 will be not supported

### ISSUE THREAD

**Issue by cr0ssmind** [kee-org/KeeFox#818]
Hi Chris & Gents!

The release date of Firefox 57 and the new API is here soon (14-10). This issue is just a kind of "do not forget" info. Btw, what is the actual status of code compatibility with v.57? Do you plan push an experimental branch for testing?

**Comment by dlech** [comment]
Duplicate of #801

**Comment by luckyrat** [comment]
Please see http://keefox.org/news/detail/2017/09/19/introducing-kee-20
