### ISSUE TITLE
Help with KeeFox

### ISSUE THREAD

**Issue by rzuch** [kee-org/KeeFox#821]
Please see http://keefox.org/news/detail/2017/09/19/introducing-kee-20

The issues that affect Kee 2.0 will be different to KeeFox 1.7 and even where the same issues affect both versions, the cause will usually be different.

Issues created or already present on this KeeFox repository will not be addressed unless they are specific to Thunderbird or serious problems affecting Firefox 52 ESR. Please get in touch privately if you find a security flaw regardless of which Mozilla application it affects to ensure a process of responsible disclosure can be followed.

If you decide to create an issue here, I hope you'll understand if it gets no response until 2018 since all our efforts are focussed on Kee 2.0. If you'd like to help KeeFox transition to version 2.0 in November 2017, please get in touch.

If the issue you are considering reporting is still relevant in Kee 2.0 please raise an issue in the new repository. For issues relating to the web browser add-on, or when you are not sure, please use https://github.com/kee-org/browser-addon/issues. For issues that affect the KeePass plugin (KeePassRPC) please use https://github.com/kee-org/keepassrpc/issues

**Comment by dlech** [comment]
For issues related to Thunderbird, please use https://github.com/kee-org/keebird/issues
