### ISSUE TITLE
Often  show up a "Authorise a new connection" window

### ISSUE THREAD

**Issue by kregielpl** [kee-org/KeeFox#822]
Hi,

Recently I've noticed a problem with KeeFox. Very often I see in a fraction of second a window with  "Authorise a new connection" dialog and it disappears. I've not changed anything. Does anyone know what cause the problem?

Thanks for advice.

**Comment by bcutter** [comment]
Came across this too. Pretty sure you set the security level to HIGH. Remove Kee addon from Firefox, reinstall it, select another security level.

**Comment by lukas-adrian** [comment]
Hi, I have also that problem. But I have two Windows Accounts (one without keepass). When switch to the user with keepass at first I have to close my Browser than switch it. The request comes from the other Windwos-Account. Is really stupid.
