### ISSUE TITLE
Problem with Kee and Bitbucket FF57

### ISSUE THREAD

**Issue by dcardin** [kee-org/KeeFox#824]
Hi! I think when all the wrinkles are gone, it will be great!
Here's an example site that used to work and now the form login is not detected. 
**https://bitbucket.org/account/signin/** 

I even updated the preferences to add aid-login-form to whitelist the form id, but it still doesn't work.
Thanks!

**Comment by auanasgheps** [comment]
Hi 
If the issue is related to Kee 2.0 plase open an issue here: 
https://github.com/kee-org/browser-addon
The _KeeFox 1.x_ repository can be considered ceased, in favour of new Kee

**Comment by dcardin** [comment]
https://github.com/kee-org/browser-addon/issues/79
