### ISSUE TITLE
Latest Kee 2.0.0.25 fails to fill credentials with Firefox 57 on specific site

### ISSUE THREAD

**Issue by juxeii** [kee-org/KeeFox#825]
Hi,

I have credentials for this website: https://www.dwservice.net/
Everything was working fine until today Firefox 57 came out.
Now when opening the above website, Kee does not fill anything.
Kee will fill the credentials only when you open a different tab and switch back to the site.
Can someone confirm this?

Thx,
Juergen

**Comment by dlech** [comment]
This repository is for KeeFox 1.x. Please open issues for Kee 2.x at <https://github.com/kee-org/browser-addon/issues>.
