### ISSUE TITLE
TB58 freezes with KeeFox "options"

### ISSUE THREAD

**Issue by r2evans** [kee-org/KeeFox#827]
When I upgraded from TB52 to TB58b2, I assumed that I should use Kee 2.0, so I uninstalled keefox-1.7.2 and went forward. When I found that [Kee 2.0 is not supported in TB](https://github.com/kee-org/browser-addon/issues/103#issuecomment-346475983), I opted to downgrade to 1.7.2, however, I'm unable to set the options: when I click on keefox's "Options" button on the add-ons page, the entire TB interface freezes and requires hard-killing (no key sequence seems to show the options modal and/or break out of it).

(The problem may not be the same, but when MarkdownHere showed a similar problem in FF, I [found a workaround](https://github.com/adam-p/markdown-here/issues/415#issuecomment-292221971) that involved a bit of debugger code. Just a thought. I've not found a way to find something similar for KeeFox.)

I believe this is not relevant for Kee 2.0.

I realize this may be a lower priority than your current efforts on Kee 2.0. Thanks for your efforts!

Versions: keefox-1.7.2, TB 58b2, win10_64

**Comment by dlech** [comment]
See https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57
 (This applies to any TB57+ problems).

**Comment by r2evans** [comment]
I had seen that page but since it says *"still support these add-ons if the appropriate modifications are done"*, I interpret it to mean that this was not an immediate factor. Do I need to try TB57 to help nail things down?

(The interfaces listed as removed, changed, etc, are a bit foreign to me. I don't know which API changes on that page may be impacting this issue.)

**Comment by dlech** [comment]
There was one section about an options bug that was being fixed, but I didn't read it yet.

**Comment by dlech** [comment]
This issue has been moved to the new KeeBird repository. Please subscribe to https://github.com/kee-org/keebird/issues/1 for further TB >= 57 compatibility updates.
