### ISSUE TITLE
Create a "start recording multi-page login process now" button

### ISSUE THREAD

**Issue by luckyrat** [kee-org/KeeFox#92]
You could click on this before submitting the first page of a login. 

This will be useful when a multi-page login starts with a form that contains no password.

Currently, KeeFox cannot fill multi-page forms that start with a password - that situation will need to change before this ticket can be implemented.

**Comment by Hello71** [comment]
I have found that KeeFox still does not accurately detect multi-page logins that start with only a plain text field (for username), similar to the new Google login format. It seems to be unable to automatically fill the login forms of [Oaken Financial](https://online.oaken.com/cb/pages/jsp-ns/login-cons.jsp) and [Meridian Credit Union](https://banking.meridiancu.ca/Security_Login).

**Comment by Hello71** [comment]
I lied, Oaken's works but Meridian's doesn't.
